- configure.ac
- doc/storaged-docs.xml
We need to fix the links in the documentation so they point to the (future) new pages.
> Fix links for the documentation

- src/storagedlinuxdrive.c
ID_SCSI_SERIAL is not always set, apparently, for example with
sg3-utils-udev on Debian.
> drives: Try harder when looking for a serial number

- modules/lvm2/storagedlinuxlogicalvolume.c
> LVM2: Correctly retrieve meta data size

- packaging/Makefile.am
- packaging/generate
This is just a copy of the generate script from the old master branch. I need this for the "CI" to work properly.
> Packaging: Add the spec file generating script

- src/tests/dbus-tests/test_60_partitioning.py
More dbus tests for partition and partition table.
> DBus tests for Partition

- src/udiskslinuxblock.c
There is no reason to expect any particular symlink, anything in
/dev/md/ is fine.
> core: Prefer nice device names also for mdraid partitions

- src/udiskslinuxprovider.c
When hot-unplugging a SATA disk, udev sends a sequence of events: first a "change" and then "remove". Storaged reacts to the "change" event by creating a new drive object on the bus. Since there is no vendor, model and serial device info, the path of the new object is some fallback one ("/org/freedesktop/UDisks2/drives/drive") and this is the object that also gets deleted by the subsequent "remove" action. The original drive object is never removed and storaged attempts to perform housekeeping on it, resulting in various errors.
The patch prevents the creation of the new drive object on the "change" event. It's actually odd to create a new device on such occasion. I don't know in what situation would such a something be necessary...
> core: don't add new drive object on "change" uevent

- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
More tests for LVM plugin and some cleanup/fixes for lvm and block tests.
> DBus tests for LVM plugin

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_30_iscsi.py
These little fixes improve the chances the tests run fine.
> Test improvements

- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_70_encrypted.py
Tests for encrypted devices and one fix for partitioning tests.
> DBus tests -- encrypted

- configure.ac
- packaging/storaged.spec.in
- src/Makefile.am
- src/udiskslinuxswapspace.c
> Use libblockdev swap plugin for swapspace

- src/tests/dbus-tests/run_tests.py
Otherwise the daemon fails to aquire the DBus name unless the configuration file
exists in the system (IOW, storaged is installed) which shouldn't be required by
the tests.
> Install the DBus config file for tests

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxpartitiontable.c
I've found few bugs when rewriting the partitioning code to use libblockdev. These should be fixed on master too. I've also adjusted dbus tests to test these features.
> Few partitioning related fixes

- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_loop.py
added tests for following Dbus api functions:
* Loop.Delete
* Loop.SetAutoClear
> Added Loop device tests

- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_90_swapspace.py
added tests for following Dbus api functions:
* Drive.Eject
* Drive.PowerOff
* Drive.SetConfiguration
* Swapspace.Start
* Swapspace.Stop
> Added drive and swapspace tests

- src/tests/dbus-tests/test_job.py
Two fixes for the Job interface tests.
> DBus tests Job fixes

- modules/bcache/udiskslinuxblockbcache.c
- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_bcache.py
First commit (_Fix PolicyKit..._) is from #162
> DBus tests for bcache module

- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
Test some more filesystems, luks and block stuff.
> Add some missing dbus tests

- src/tests/dbus-tests/test_btrfs.py
Btrfs sucks at producing proper uevents. From the tests failures it looks like
uevents are either not produced at all on many changes or before signatures are
actually written to disk. If we synthesize our own artificial 'change' events on
devices that should get them, we suddenly start getting correct values.
This needs a real fix somewhere. Either in the code so that we somehow deal with the weird
behavior of btrfs (which is however much more work than we can spend on this
now) or somewhere in kernel/btrfs, because these issues seem to only happen with
rawhide kernels.
So let's just use this quick and dirty solution to make tests passing for now
and we will get back to the real issue here later.
> Fix failing btrfs tests

- Makefile.am
- packaging/storaged.spec.in
> Makefile improvements for tests

- packaging/udisks2.spec.in
- src/udiskslinuxmanager.c
> Minor fixes for mdraid code

- data/org.freedesktop.UDisks2.xml
- src/tests/integration-test
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxencrypted.c
As discussed in #184.
BTW: Should we also allow adding/removing passphrases?
> Keyfile support for ChangePassphrase

- AUTHORS
- Makefile.am
- NEWS
- configure.ac
- packaging/udisks2.spec.in
Post release version bump to 2.6.5 and two small fixes in `AUTHORS` and `Makefile`.
> 2.6.4 post release

- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/udiskstestcase.py
- src/tests/integration-test
- src/udiskslinuxfilesystem.c
Use libblockdev FS plugin `bd_fs_mount` and `bd_fs_unmount` functions instead of `mount` and `umount` programs.
> Use libblockdev for (un)mounting

- packaging/udisks2.spec.in
This will make fedpkg happy again.
> Fix bogus date in changelog

- src/udisksstate.c
Remove duplicate code in `udisksstate.c`.  More could be done here.
> Remove duplicate code in udisksstate.c

- modules/zram/data/org.freedesktop.UDisks2.zram.xml
- modules/zram/udiskslinuxblockzram.c
- modules/zram/udiskslinuxmanagerzram.c
- src/tests/dbus-tests/test_zram.py
- src/udisksdaemon.c
- src/udisksdaemon.h
zRAM module API updated to be consistent with rest of UDisks
> Fix API for the zRAM module

- README.md
These are useful bits of information to know when getting started.
> README.md: Add development notes

- src/tests/dbus-tests/test_90_swapspace.py
Use Udisks to create the swap format for "test_20_start_stop"
because this way udisks will actually wait until the swap is
created and we don't need to do sleep/udev settle before trying
to activate it.
> Fix failures in swap tests

- AUTHORS
- HACKING
Add everyone that has committed at least 1 commit to this file
to encourage others to contribute too.
Note: Info collected with `git shortlog -se`
> Update AUTHORS file

- TRANSLATING
We have po files in the repo and some translators tried to open
PRs to update them -- we need something to direct them to Zanata.
> Add readme for translators

- src/udiskslinuxblock.c
Because it is more reliable than using from udev.
> Use libblockdev to get LUKS UUID for LUKS open

- src/tests/integration-test
- udisks/udisks-pygi-example.py
- udisks/udisksclient.c
Removed some duplicate code from `udisksclient.c` and added a unit test for what was changed.  Also cleaned up the `udisks-pygi-example.py` so that is would run without errors.
> Remove duplicate code from udisksclient.c

- HACKING
- doc/udisks2-docs.xml.in.in
- New link for the latest documentation.
- Add documentation update to release checklist
> Documentation and HACKING update

- modules/lvm2/udiskslinuxlogicalvolume.c
Place common initialization and checking code into a function called `common_setup`.  I tried making a common function with numerous callbacks to virtually replace the implementation of all these functions with one, but that got too unwieldy so going with this simple change instead.
> udiskslinuxlogicalvolume.c: Dupe code removal

- src/udiskslinuxpartition.c
While looking around in the code it's pretty apparent that there is **a lot** of copy and pasted code.  I'm not sure what others think about this, but I personally try to avoid it.  I took one file and worked on it a little bit today, to see what I could do.
This has only been compiled, likely I've introduced a number of bugs.  If people would like to reduce the source code size and feel better that when they fix a bug they don't have to grep the entire source base to ensure the bug isn't duplicated somewhere else I will work on this some more.  Otherwise we can toss this PR and keep doing what we are doing.
> DRY: Don't Repeat Yourself

- src/udisksdaemon.c
Use a common function for the same code which is used in a few
different places.
> udisksdaemon.c: Use common function for job creation

- src/udiskslinuxblock.c
I experimented with using a common authentication function, but in the end the changes to support that outweigh code saving and complexity savings.  Some functions are calling into authenticate multiple times.  Furthermore trying to make a common authentication function across the code base is hampered in the different ways it occurs and the amount of associated data would need to be returned as well.
> udiskslinuxblock.c: Use common device handling func.

- modules/lvm2/udiskslinuxvolumegroup.c
Remove copy & pasted code from the file `udiskslinuxvolumegroup.c`.
While doing this change I did discover that the function `handle_create_thin_volume` was calling ` udisks_volume_group_complete_create_thin_pool_volume` instead of `udisks_volume_group_complete_create_thin_volume`.
One of the hazards of copy & pasting code.  However, in this case no external visible bug was experienced.
> Linux volume group dupes

- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
- modules/lvm2/udiskslinuxlogicalvolume.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
- src/tests/dbus-tests/test_20_LVM.py
For active LVs add a property with object path of the block
device for this LV.
> Add a 'BlockDevice' property for 'org.freedesktop.UDisks2.LogicalVolume'

- modules/bcache/udiskslinuxblockbcache.c
- modules/iscsi/udisksiscsiutil.c
- modules/iscsi/udiskslinuxiscsisessionobject.c
- modules/lsm/lsm_linux_drive.c
- modules/lvm2/jobhelpers.c
- modules/lvm2/udiskslinuxmanagerlvm2.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
This fixes a number of issues that coverity flagged, I've written up issues for the others.
> Coverity fixes

- src/tests/dbus-tests/test_60_partitioning.py
Make the extended partition large enough to fit both logical
partitions we are adding and remove the second logical partition
during cleanup.
> DBus tests: Fix extended partition test case

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxpartitiontable.c
~~This needs the tests that failed to reveal the issues to be updated.~~ [DONE]
> Partition creation fixes

- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxblock.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxfilesystem.c
Pretty straight forward changes, may want to move some of the functions is a more appropriate file?
> Remove duplicated code for block & filesystem and udiskslinuxdriveata.c

- udisks/udisksclient.c
The client library was missing the job description
for "filesystem-check" and "filesystem-repair".
Sorry, I missed that in the respective PR ;)
> Include Job Descriptions for FS Check/Repair

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxblock.c
- src/udiskslinuxpartitiontable.c
- src/udiskslinuxpartitiontable.h
This property contains list of object paths to all partitions on
this device.
> Add a new "Partitions" property to "PartitionTable" interface

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_10_basic.py
- src/udiskslinuxmanager.c
> Add a function to list all block devices

- src/udiskslinuxencrypted.c
This should fix failing `integration-test` on Rawhide.
> Wait for cleartext device object to disappear on Lock()

- udisks/udisksclient.c
> udisksclient.c: Fix a typo

- src/tests/dbus-tests/test_80_filesystem.py
We need separate test cases for creating filesystem with label and
for setting label on an existing filesystem. There are some
filesystems (for example UDF) that supports setting label when
creating but not changing it later.
Fixes #361
> FS tests: Split label test into two

- data/org.freedesktop.UDisks2.xml
This functions has been added in 2.7.2
> Add version info to docstrings of the partition Resize function

- src/tests/dbus-tests/test_bcache.py
BcacheCreate sometimes fails in a way that the bcache device is
actually created. We need to try to delete this bcache device so
it doesn't affect other tests.
> Bcache tests: Cleanup when BcacheCreate() fails

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/udiskstestcase.py
These often provide very interesting information about what was
happening in the system and with the udisksd daemon during the
tests. Also add journal because it also provides potentially
useful information.
> Gather records of udev and udisksctl monitors for tests

- src/udiskslinuxblock.c
- src/udiskslinuxfsinfo.c
> Misc udf and partition type fixes

- packaging/udisks2.spec
> Own the %{_libexecdir}/udisks2 dir

- src/udiskslinuxpartition.c
During Partition.Resize() the device node shortly
disappears and bubbles up again through udev and
the interfaces of the object are set up anew.
The method will now wait for the partition
property to be updated with the new size.
This depends on the unreleased
https://github.com/storaged-project/libblockdev/commit/7ffc9746f77d96d06c497e260d3ea042c52e1888
> Process partition resize update before return

- src/udiskslinuxloop.c
> Fix uninitalized value in "udisks_linux_loop_update"

- src/tests/dbus-tests/test_job.py
Erasing the device sometimes takes a really long time. We don't
have to wait for it it finish -- we just need the job object and
we can cancel the job after checking its properties.
> Ignore timeout in job tests

- src/tests/dbus-tests/test_btrfs.py
'subvolumes list' outputs non-existent subvol after removing
a subvolume.
> Skip btrfs subvolume tests with btrfs-progs 4.13.2

- src/Makefile.am
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/udiskstestcase.py
- src/udiskslinuxmdraid.c
- src/udiskslinuxmdraidhelpers.c
- src/udiskslinuxmdraidhelpers.h
- src/udiskslinuxmdraidobject.c
> Do not try to create file watchers for RAIDs without redundancy

- src/tests/dbus-tests/test_drive_ata.py
The exit status of 'smartctl' is a bit mask. Only two of those
bits mean the device failed to provide valid SMART data, others
mean different things (device failing,...). We should thus only
check those two bits when filtering devices supporting SMART.
Resolves: #423
> Fix how we check the exit status of 'smartctl' in tests

- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_90_swapspace.py
- src/tests/dbus-tests/test_btrfs.py
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/test_zram.py
- src/tests/dbus-tests/udiskstestcase.py
See commit message of the first commit for details.
> Marking unstable tests

- src/udisksstate.c
When the mount point includes a symlink (e.g. symlinking /media to
/run/media) things get when comparing mountpoints as one is using the
canonical path while the other is not.
Resolve this by canonicalizing the mountpoint before further processing.
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
> Resolve mountpoint to the real path

- src/tests/Makefile.am
> Add dbus tests into the source archive

- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
> Fix opening devices with crypttab entry

- src/udiskslinuxprovider.c
libudev has the udev_device_get_is_initialized() method that does
this::
Check if udev has already handled the device and has set up
device node permissions and context, or has renamed a network
device.
This is only implemented for devices with a device node or
network interfaces. All other devices return 1 here.
We should wait for such initialization to finish before we start
probing the device because otherwise we have a race condition and
may get outdated data or maybe even some temporary garbage. And
we should do this in the thread that can wait without blocking
the main loop.
Related: #448
> Wait for device to become initialized before probing it

- src/tests/dbus-tests/test_60_partitioning.py
This should fail now, https://github.com/storaged-project/libblockdev/pull/306 needs to be merged first
> Add test to check GUID/type after GPT partition flags change.

- src/tests/dbus-tests/test_20_LVM.py
Check that we report same size that LVM reports.
--------
We already had two issues with wrong size of thinpools (#472 and #106) so we really need a test for this.
> Check size of created thinpool in tests

- src/main.c
Revert https://github.com/storaged-project/udisks/commit/d9f7b05bf73ab193c8778a8bb34e52e0e677c0a4 and properly fix the critical warning.
> main.c: Properly remove sigint source

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
- added a property for LUKS metadata size
- added a test for LUKS metadata size
> New property for LUKS metadata size

- data/80-udisks2.rules
Contains drivers and tools only relevant to Windows
> Ignore Nokia 7 Plus virtual CD

- modules/lvm2/udiskslinuxlogicalvolume.c
- src/tests/dbus-tests/test_20_LVM.py
We are not testing properties in LVM tests and we already had multiple some bugs with wrong size so it's better to check everything we can.
I've also found that we don't wait for the LV object to disappear after *Deactivate* and *Delete* so I fixed that too.
> LVM tests improvement

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfsinfo.c
> Allow changing label on udf filesystems

- data/org.freedesktop.UDisks2.xml
- packaging/udisks2.spec
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
- src/udiskslinuxblock.h
- src/udiskslinuxencrypted.c
New version of #530 with locks (should prevent crashes on CentOS 7).
> LUKS metadata size

- src/udiskslinuxblock.c
TrueCrypt and VeraCrypt support multiple encryption of volumes (see
https://www.veracrypt.fr/en/Cascades.html). When such a volume is
unlocked, a separate device-mapper device is created for each encryption
layer. For triple-encryption, the dm tree looks like this:
tcrypt-1793 <dm-3> (254:3)
└─tcrypt-1793_1 <dm-2> (254:2)
└─tcrypt-1793_2 <dm-1> (254:1)
└─ <loop1> (7:1)
The first two devices (dm-1 and dm-2) are not listed by udisks (because
of udev flags I think), but the actual cleartext device (dm-3) is.
When a device is unlocked, the crypto backing device property is set by
iterating through all devices and checking whether the backing device is
a child (slave). This didn't work, because the parent device (dm-1) was
not listed by udisks - and the actual cleartext device (dm-3) is not …
> Fix backing device not set when unlocking multiple encrypted volume

- src/udisksconfigmanager.c
This is just a little cleanup and refactoring to keep maintainability on a sane level. No functional changes.
Fixes: #561
> Configmanager cleanup

- src/tests/dbus-tests/test_vdo.py
- src/tests/dbus-tests/udiskstestcase.py
> VDO test fixes

- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/test_zram.py
> mdraid and zram test fixes

- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/udiskstestcase.py
- src/udiskslinuxencrypted.c
> Fix reading passphrase from key file specified in crypttab

- src/udiskslinuxblock.c
- src/udiskslinuxblockobject.c
- src/udiskslinuxblockobject.h
Not a 100% bulletproof solution, should fix most cases however.
> Fix org.freedesktop.UDisks2.Filesystem presence race conditions

- src/tests/dbus-tests/test_70_encrypted.py
LUKS2 resize needs passphrase only if the key is stored in the
kernel keyring. This is not supported on older kernels where the
key is stored in the dm table and passphrase is not needed for
resize.
> Fix LUKS2 resize password test

- data/org.freedesktop.UDisks2.xml
- doc/udisks2-sections.txt.in.in
- modules/lsm/lsm_local.c
- modules/lsm/lsm_module_iface.c
- modules/vdo/udiskslinuxmanagervdo.c
- src/tests/test.c
- src/udisksdaemon.c
- src/udiskslinuxmdraid.c
- src/udiskslinuxmdraidobject.c
- src/udiskslinuxprovider.c
- src/udiskslinuxswapspace.c
- src/udisksspawnedjob.c
- src/udisksthreadedjob.c
- src/udisksthreadedjob.h
Various fixes collected by running the test suite.
Fixes: #324
> Leaking fds

- src/tests/dbus-tests/test_70_encrypted.py
We have changed the error mesage in https://github.com/storaged-project/libblockdev/pull/412 and I forgot to fix the second *location* typo before merging #612
> Two small LUKS tests fixes

- modules/iscsi/udiskslinuxmanageriscsiinitiator.c
- modules/lvm2/udiskslvm2daemonutil.c
- src/udiskslinuxblock.c
- src/udiskslinuxblockobject.c
- src/udiskslinuxdevice.c
- src/udiskslinuxdrive.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxmanager.c
- src/udisksstate.c
Please see the second commit message.
One other idea that crossed my mind was to use GObject properties that would hopefully give more atomicity, however I don't believe it would fix the root issue fully.
> Fix GUdevDevice race conditions

- src/Makefile.am
Small cleanup for src/Makefile.am
> Cleanup some indentation errors from src/Makefile.am

- src/udiskslinuxfilesystem.c
> Add 'windows_names' as a default mount option for ntfs-3g

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/udiskstestcase.py
- src/udiskslinuxfsinfo.c
- src/udiskslinuxfsinfo.h
- src/udiskslinuxmanager.c
For the benefit of UIs such as Cockpit.
> Expose supported encryption types and their default

- README.md
- src/tests/dbus-tests/run_tests.py
- src/tests/install-udisks/runtest.sh
- src/tests/integration-test
Small test fixes found by using tarball sources rather than compiled git sources
> Test fixes2

- src/udiskslinuxpartition.c
WIP for now, one more round to test.
> covscan fixes

- modules/btrfs/udiskslinuxfilesystembtrfs.c
- src/udisksspawnedjob.c
- tools/udisksctl.c
Did a full coverity scan over git master. There was lots of false positives, among one real problem.
Closes: #304
> Covscan fixes 2

- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxdrive.c
- src/udisksstate.c
Fixed version of https://github.com/storaged-project/udisks/pull/623 - one should really test again after changing "only cosmetic" things.
> use g_shell_quote for inputs to g_shell_parse_argv

- src/tests/dbus-tests/udiskstestcase.py
On Debian version in OperatingSystemPrettyName looks like
'bullseye/sid' which is not really usefull and we should try to
use LSB which says 'testing'.
---
This is copied from libblockdev, see https://github.com/storaged-project/libblockdev/blob/master/tests/utils.py#L228
> dbus-tests: Try to read distro version from LSB

- README.md
> Fix spelling of UDisks in README

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
These devices can be unmounted by any user so we shouldn't ask for
passphrase and just unmount it as the calling user.
Fixes #709
> Fix unmounting devices mounted with the "users" option in fstab

- modules/lvm2/udiskslinuxvolumegroupobject.c
- src/udisksdaemonutil.c
- src/udiskslinuxblock.c
- src/udiskslinuxencryptedhelpers.c
- src/udiskslinuxfilesystemhelpers.c
- src/udiskslinuxmdraid.c
- src/udiskslinuxpartitiontable.c
- src/udisksspawnedjob.c
- src/udisksutabmonitor.c
- tools/udisksctl.c
Just a follow up on the last pull request...
> Code style cleanup: comments

- po/cs.po
- po/fur.po
- po/it.po
- po/pt.po
- po/pt_BR.po
- po/sk.po
- po/tr.po
Pulled from Zanata while it still works.
> Translation updates

- modules/btrfs/udiskslinuxfilesystembtrfs.c
- modules/btrfs/udiskslinuxmanagerbtrfs.c
- src/tests/dbus-tests/test_btrfs.py
- src/udiskslinuxblock.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxpartition.c
- src/udiskslinuxpartitiontable.c
> Synthetic uvent tagging - continued, minor fixes #1

- doc/man/udisks.xml.in
Let's hope this one will stay alive.
Fixes: #758
> man: Fix documentation link for libudev

- src/tests/dbus-tests/test_80_filesystem.py
> Add a test for the no-discard option for Format

- data/builtin_mount_options.conf
- src/tests/dbus-tests/test_btrfs.py
> Add allowed mount options for btrfs and f2fs

- src/udiskslinuxblock.c
- src/udisksstate.c
> Memory leak fixes

- src/tests/dbus-tests/test_20_LVM.py
1 GiB suddenly isn't enough for physical size grow, lets hope
2 GiB will be enough for everyone.
Resolves: rhzb#1845435
> dbus-tests: Fix UdisksLVMVDOTest.test_resize_physical

- src/tests/dbus-tests/test_drive_ata.py
> dbus_tests: Fix getting list of SATA drives for Drive.ATA test

- data/builtin_mount_options.conf
Just a bit of a cleanup of my kanban board. Not 100% sure about the `acl` option though.
> Configurable mount options misc 1

- doc/udisks2-sections.txt.daemon.sections.in
- src/udisksdaemon.c
- src/udisksmodulemanager.c
- src/udisksstate.c
- src/udisksstate.h
> Modularity: crash recovery

- doc/udisks2-sections.txt.daemon.sections.in
- src/tests/dbus-tests/test_50_block.py
- src/udisksfstabentry.c
- src/udisksfstabentry.h
- src/udiskslinuxblock.c
https://gitlab.gnome.org/GNOME/gvfs/-/issues/527
> Honour 'noauto' fstab option for Block.HintAuto computation

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystemhelpers.c
> Fix TakeOwnership symlinks traversal

- src/udisksstate.c
Just a tiny change to use recently merged infrastructure.
> udisksstate: Use udisks_daemon_util_trigger_uevent()

- doc/udisks2-sections.txt.daemon.sections.in
- src/udiskslinuxdevice.c
- src/udiskslinuxdevice.h
- src/udiskslinuxmdraid.c
- src/udiskslinuxmdraidhelpers.c
- src/udiskslinuxmdraidhelpers.h
- src/udiskslinuxmdraidobject.c
UDisks 2.10 material. Originally intended for broader use, unused at the end. Still I think it's worth having this, but didn't want to spoil the stable branch.
> Slight sysfs reading refactoring

- src/udiskslinuxfilesystemhelpers.c
- src/udiskslinuxmdraidobject.c
A bunch of fixes as found by Coverity, very little chance to hit in a real world scenarios. Perhaps not even worth of fixing some of them...
> Covscan fixes 3

- src/tests/dbus-tests/Makefile.am
Also make sure it's rebuilt every time as re-configure with
different options wouldn't rebuild it.
> tests: Do not dist config_h.py

- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
- modules/lvm2/udiskslinuxlogicalvolume.c
- src/tests/dbus-tests/test_20_LVM.py
> Set LogicalVolume.Type to "vdopool" for LVM VDO pools

- src/udiskslinuxencrypted.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxpartition.c
- src/udiskslinuxpartitiontable.c
Couple of minor issues found by reviewing the code. Mostly error paths, still based on existing real bugreports.
> Fix GError ownerships

- configure.ac
- src/Makefile.am
- src/udisksdaemon.c
- src/udisksdaemon.h
- src/udisksdaemontypes.h
- src/udiskslinuxblock.c
- src/udiskslinuxprovider.c
- src/udisksprivate.h
For utab functionality, making it unconditional.
> daemon: Require libmount >= 2.30

- src/tests/dbus-tests/test_80_filesystem.py
This proved to be unreliable as expected, not even after explicit
sleep the daemon managed to register mountinfo changes. Not a critical
set of tests, let's just disable that for the moment.
> tests: Disable filesystem _test_fstab_label external mount tests

- modules/lvm2/udiskslinuxmodulelvm2.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
> lvm2: Only install results of most recently started udpates

- src/tests/dbus-tests/test_50_block.py
- src/udiskslinuxblock.c
"-" is also valid key file value with the same meaning as "none"
> Fix parsing key file from /etc/crypttab

- data/org.freedesktop.UDisks2.xml
> docs: Clarify the Manager.SupportedFilesystems property

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
Instead of computing it ourselves from the filesystem info. This
will also remove the need for updating this function every time
libblockdev adds support for a new filesystem.
----
New version of https://github.com/storaged-project/udisks/pull/763 Tests will fail until https://github.com/storaged-project/libblockdev/pull/759 is merged.
> Use bd_fs_get_size to get filesystem size

- data/org.freedesktop.UDisks2.xml
- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxencryptedhelpers.h
First part of the cleanup, removing the clutter, making the code clearly organized. Subject to further major changes when porting over the new `libblockdev` filesystem API (https://github.com/storaged-project/libblockdev/pull/621).
No functional changes (if everything went well).
Fixes #584
> org.freedesktop.UDisks2.Block.Format() refactor

- src/udiskslinuxnvmenamespace.c
Wrong test, leading to dereferencing NULL error.
Includes slight refactoring in job check.
> udiskslinuxnvmenamespace: Fix FormatNamespace() error check

- po/nn.po
I’m adding the translation as a pull request, since the https://fedora.zanata.org/ translation platform mentioned in the `TRANSLATING` file doesn’t seem to work anymore (and haven’t been working since 2020, according to archive.org).
If there’s an alternative translation platform I should use, I’ll be happy to do so.
> Add Norwegian Nynorsk translation

- src/udiskslinuxpartition.c
Libblockdev 3.0 is getting rid of the parted-style flags and introduces two new functions we can use instead.
https://github.com/storaged-project/libblockdev/pull/800 needs to be merged first.
> Adjust to new libblockdev part API

- src/tests/dbus-tests/targetcli_config.json
- src/tests/dbus-tests/test_30_iscsi.py
Linux kernel 6.0 brought number of LIO target changes: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/drivers/target?h=v6.0.2
> iscsi: Test fixes for linux kernel 6.0

- src/udiskslinuxnvmecontroller.c
- src/udiskslinuxnvmenamespace.c
It's not guaranteed that the UDisksThreadedJob job func will ever get called. Better to perform cleanup in the data destroy notify otherwise we may hit another race condition, leaving the job objects falsely assigned, refusing subsequent job sumbissions.
Also, employ a semaphore for a sync wait to job to finish, preventing lingering jobs finishing async after the master method call returned.
> nvme: Fix progress jobs cleanup

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_10_basic.py
- src/udiskslinuxmanager.c
> Add support for resolving devices by partlabel and partuuid

- packaging/udisks2.spec
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> spec: Change license string to the SPDX format required by Fedora

- packaging/udisks2.spec
With the transition to the new libblockdev-3.0 filesystem API the list of supported filesystems has changed a little. Additionally, something should pull in the corresponding filesystem tools so that clients can make use of the full support. For this to achieve the rpm Recommends: directive is the best bet.
https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/
> spec: Tweak the filesystem tools deps

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_loop.py
- src/udiskslinuxloop.c
- src/udiskslinuxmanager.c
See https://github.com/storaged-project/libblockdev/pull/819 for details.
> Adjust to libblockdev loop API changes

- src/tests/dbus-tests/test_20_LVM.py
Latest LVM doesn't allow shrinking inactive LVs without a special command line option.
Related libblockdev issue: https://github.com/storaged-project/libblockdev/issues/841
> tests: Do not deactivate LVs before resize in test_10_linear

- modules/iscsi/udisksiscsiutil.c
- src/tests/dbus-tests/test_30_iscsi.py
> iscsi module CHAP auth fixes

- src/tests/dbus-tests/test_80_filesystem.py
f2fs-tools-1.15 changed the information structure reported by dump.f2fs, omitting sector size reporting.
Also, unify filesystem tool version detection.
> tests: Skip f2fs sector size tests on newer f2fs-tools

- udisks.doap
https://wiki.gnome.org/Git/FAQ
https://github.com/ewilderj/doap/wiki
> Add DOAP project definition file

- src/udiskslinuxfilesystem.c
Latest addition to blkid as released in util-linux-2.39 exposes ID_FS_FSLASTBLOCK and ID_FS_FSSIZE keys carrying calculated filesystem size.
The legacy path of property value retrieval on demand is still in place in case the udev property is unavailable (or zero if unsupported filesystem type in libblkid).
> udiskslinuxfilesystem: Use udev ID_FS_SIZE if available

- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
- src/udiskslinuxencryptedhelpers.c
The crypto plugin API is going through a major overhaul in 3.0.
See https://github.com/storaged-project/libblockdev/pull/898 for details.
> Adjust to libblockdev 3.0 crypto plugin API changes

- data/builtin_mount_options.conf
> mount options: Sync ntfs3 options with kernel 6.4-rc7

- Makefile.am
- configure.ac
Driven by https://bugs.gentoo.org/871609
> automake project fixes

- src/tests/helper.c
- src/tests/test.c
> tests: Adapt to clang differences when causing a segfault

- src/tests/dbus-tests/targetcli_config.json
Not all attributes are available anymore in newer kernel versions.
> tests: Fix targetcli_config.json

- src/tests/dbus-tests/test_70_encrypted.py
> tests: Add locked LUKS teardown test

- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
> Allow using key files with BITLK devices

- src/tests/integration-test
> integration-test: Adapt to the new libmount context error messages

- misc/install-test-dependencies.yml
- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
- src/tests/dbus-tests/skip.yml
- src/tests/dbus-tests/test_20_LVM.py
See https://github.com/storaged-project/libblockdev/pull/1039 for details.
> Adjust to changes in the upstream VDO kernel module

- src/tests/integration-test
> tests: Fix expected error message with util-linux 2.41

- misc/udisks-tasks.yml
- src/tests/dbus-tests/test_loop.py
- src/tests/integration-test
> tests: Use sfdisk instead of parted to create partitions in tests
