- data/org.storaged.Storaged.xml
- src/storagedlinuxmdraid.c
Looking at MDRaid.ActiveDevices or Block.MDRaid gives the same
information, but only asynchronously.
Fixes #12
> MDRaid: Add 'Running' property.

- src/storagedlinuxprovider.c
Right before the "remove" event, the UUID of mdraid devices seems to
change sometimes.
Without catching this, we would create a new object for the new UUID
and erroneously dispatch the "remove" event to it.  Consequently, the
original object would not receive this event and would continue
watching a non-existent device.
> Catch bogus UUID changes of MDRAIDs.

- src/storagedlinuxblock.c
Wipefs is worth waiting for as it will detect whether or not the block
device is in use somewhere else.  Everything after that should only
fail when the hardware fails.
> Do the wipe before returning for a 'no-block' Format.

- modules/lvm2/storagedlinuxlogicalvolume.c
- modules/lvm2/storagedlinuxlogicalvolume.h
- modules/lvm2/storagedlinuxlogicalvolumeobject.c
- modules/lvm2/storagedlinuxlogicalvolumeobject.h
- modules/lvm2/storagedlinuxvolumegroupobject.c
Previously, we would read them only when a logical volume needed
updating because of a udev event.  Now we read them when they change.
Fixes #17
> lvm2: Properly monitor fstab and crypttab.

- configure.ac
- doc/Makefile.am
- doc/man/Makefile.am
- doc/man/storaged_lsm.conf.5.in
- doc/storaged-docs.xml.in.in
- doc/storaged-docs.xml.lsm.dbus.in
- doc/storaged-docs.xml.lsm.sed
- modules/Makefile.am
- modules/lsm/Makefile.am
- modules/lsm/README_DEV_lsm.txt
- modules/lsm/TEST_NOTE_lsm.txt
- modules/lsm/data/Makefile.am
- modules/lsm/data/org.storaged.Storaged.lsm.xml
- modules/lsm/data/storaged_lsm.conf
- modules/lsm/lsm_data.c
- modules/lsm/lsm_data.h
- modules/lsm/lsm_linux_drive.c
- modules/lsm/lsm_linux_manager.c
- modules/lsm/lsm_module_iface.c
- modules/lsm/lsm_types.h
- rpm_dependencies.txt
- src/storagedlinuxdriveobject.c
- src/storagedlogging.c
New lsm module using LibStorageMgmt API.
* Using LibStorageMgmt API to query external(DAS and SAN) storage RAID
information and expose it via "org.storaged.Storaged.Drive.LSM" interface.
The manpage included "storaged_lsm.conf(5)" include details.
* Workflow:
* Build in LibStorageMgmt URI:
* sim://
Using simulator of LibStorageMgmt, for develop only.
Disabled by default.
* hpsa://
For HP SmartArray. Enabled by default. Require 'hpssacli' binary
tool installed. The 'libstoragemgmt-hpsa-plugin' is also required.
Check "storaged-lsm.conf(5)" manpage for detail.
* Extra LibStorageMgmt URI can be defined in storaged-lsm.conf like:
extra_uris = ["ontap+ssl://root@ontap.a.ip", "ontap://root@nb.ip"]
extra_passwords = ["password_string_1", "password_string_2"]
* Matching storaged Linux drive using …
> Patch V3: New module -- lsm: Use LibStorageMgmt for RAID information.

- configure.ac
- modules/lvm2/data/org.storaged.Storaged.lvm2.xml
- modules/lvm2/storagedlinuxlogicalvolume.c
- modules/lvm2/storagedlinuxmanagerlvm2.c
- modules/lvm2/storagedlinuxvolumegroup.c
- modules/lvm2/storagedlvm2daemonutil.c
- modules/lvm2/storagedlvm2daemonutil.h
LVM cache uses LVM2 tools to create cache LV, logical volume type which consists of small and fast LV (Cache Pool LV) and a large and slow LV (Origin LV). Performance of Origin LV is improved by storing the frequently used blocks on Cache Pool LV.
> LVM2: add LVMCache support

- data/80-storaged.rules
- modules/zram/Makefile.am
- modules/zram/data/Makefile.am
- modules/zram/data/zram-setup@.service
- modules/zram/storagedlinuxblockzram.c
- modules/zram/storagedlinuxmanagerzram.c
- modules/zram/storagedzramutil.c
- modules/zram/storagedzramutil.h
Adding/removing of zram devices sets files which are responsible for following process:
After reboot there is zram kernel module loaded with number of devices stated in modprobe. Device adding will evoke service run, which sets disksizes and number of compresson streams and optionally makes swaps from zram devices.
> ZRAM: add configuration for setup after reboot

- modules/lvm2/data/org.storaged.Storaged.lvm2.xml
- modules/lvm2/storagedlinuxvolumegroup.c
So that the 'size' argument to the CreateThinPoolVolume really
specifies the total amount of space taken out of the volume group, as
intended.
> lvm2: Use "NNN%FREE" syntax when creating thin pools

- modules/lvm2/data/org.storaged.Storaged.lvm2.xml
- modules/lvm2/storagedlinuxlogicalvolume.c
- modules/lvm2/storagedlvmhelper.c
To match how CreateThinPool interprets the size.
> LVM2: Include metadata size in Size property.

- src/storagedlinuxpartitiontable.c
This bug was introduced when porting 5c859c from udisks2 as eb4b99.
In storaged, the method is not completed in the utility function
storaged_linux_partition_table_handle_create_partition, but in the
actual method handlers handle_create_partition and
handle_create_partition_and_format.
Completing the method invocation twice causes the client to miss any
later error messages.
> Core: Don't complete partition/format methods twice

- src/storagedlinuxblock.c
Although a better handling of no-block errors would be nice, at
the very least we should be logging these failures and not dropping
the failure messages on the floor.
> Log failures when formatting or creating partitions

- modules/iscsi/data/org.storaged.Storaged.iscsi.xml
- modules/iscsi/storagedlinuxmanageriscsiinitiator.c
So that clients like Cockpit can adapt accordingly.
> ISCSI: Add SessionsSupported property

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_30_iscsi.py
These are just the basic LVM and iSCSI tests borrowing lot of code and ideas
from the integration_test already present in the tree. The tests are by no
means complete and would need to be extended. They intentionally don't rely on
the gi python module.
The tests are meant to be run on a dedicated machine: they connect to the system
bus and may disrupt the running system.
> Tests: Add basic D-Bus tests for LVM and iSCSI

- src/tests/dbus-tests/run_tests.py
This should save some of the manual work when trying to run the
tests: Let's save the old polkit data files, install the ones from
the source tree and then restore the saved ones at the end of
the testing. Not perfect but simplifies switching between branches.
> Tests: Install and eventually backup the polkit data files

- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
- modules/lvm2/udiskslinuxlogicalvolume.c
Storaged still uses the unsafe '--splitcache' option. Here's the fix not depending on libblockdev. We may eventually switch to libblockdev backend once it has all the features. Until then this should be sufficient.
> Fix #46: LVM2 Plugin: cache split using unsafe option

- src/udiskslinuxdriveobject.c
- src/udiskslinuxprovider.c
When the system suspends or hibernates the ATA drives reset their configuration to default. This for example resets the APM level. This is an attempt to fix the problem. Storaged subscribes to logind D-Bus signal sent on system suspending or resuming and on resume event scans the drive configuration files and for each such drive synthesizes a fake "reconfigure" event that makes the uevent handling routines to apply the configuration settings again. Looks to fix the issue #72 on my system.
> Core: Force re-applying configuration on system resume from sleep

- src/udiskslinuxprovider.c
There was a silly omission in the previous patch... I did a too heavy cleanup. Apologies.
> Core: Fix FTBFS caused by error in udiskslinuxprovider.c

- Makefile.am
- packaging/storaged.spec.in
Just for convenience and ease of testing: make rpm now creates packages in the 'packaging' subdirectory.
> Build system: Add rpm make taget

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/test_10_basic.py
These are two patches: first calls the EnableModules method in the first test te ensure the rest of the test suite works and the second adds option not to replace the system daemon and run the tests on the installed one.
> Add option to test also the system installed storaged instance

- src/udiskslinuxblock.c
This is a tiny regression introduced by the commit 5f22a02d and causing the integration tests to fail. Storaged should return the "NotSupported" error instead of "Fail" when trying to label a file system that does not support labels.
> Core: Return correct error type on unsupported FS label

- src/tests/dbus-tests/test_20_LVM.py
This fixes mysterious test failures. Turned out it only takes time for the LV resize change to get propagared to the D-Bus objects.
> Tests: Sleep before querying resized LV

- Makefile.am
- packaging/storaged.spec.in
Here's another attempt to create testing rpm packages from git tree with automatic versioning. This time it's purely in the spec file: if the rpmbuild command is run from within the git tree the resulting rpm is versioned by the git hash. The usual release version is used otherwise.
I have also created a srpm target to avoid re-building the binary rpms when preparing a source package for other build services (COPR).
> Build: Add srpm make target; autogenerate rpm versions from git hash.

- src/udiskslinuxdriveobject.c
The return of `g_dbus_object_get_interface()` should be freed.
> Fix memory leak caused by g_dbus_object_get_interface()

- modules/bcache/udisksbcachemoduleiface.c
- modules/btrfs/udisksbtrfsmoduleiface.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
- modules/lvm2/udiskslvm2daemonutil.c
- modules/lvm2/udiskslvmhelper.c
- modules/zram/udiskszrammoduleiface.c
- src/udiskslinuxdriveata.c
With these changes the daemon can make it through the lvm dbus test without leaking tons of memory or running out of file descriptors, assuming it doesn't seg. fault before we are done.  There are at least 2 distinct seg. faults that I'm aware of that still exist, and I will **try** to track them down too.  Just to clarify, the daemon's dbus API is not being exercised, it's just responding to udev events which occur during the lvm dbus unit test.
The fix in this PR for the seg. fault prevents the crash of the lvm helper, but we need to understand why we are failing from lvm2app.  I'm also seeing warning where the lvm helper is failing to retrieve information, so the dbus objects will be incorrect.
> Misc fixes

- modules/lvm2/udiskslvm2daemonutil.c
This is a cosmetic fix for the PR #90.
> LVM2: Use g_strerror insted of strerror_r

- src/udiskslinuxpartition.c
The previous code could produce names like "/dev/loop123" for
partition number 3 on device "/dev/loop12", which libblockdev would
parse as partition number 123.  Just use the path name in the
filesystem, which is supposedly what liblockdev expects.
Fixes #97
> core: Don't pass bogus partition names to libblockdev

- src/udisksconfigmanager.c
The GError should be freed when `g_key_file_load_from_file()` or
`g_key_file_get_string()` failed.
> Fix memory leak in udisks_config_manager_constructed()

- src/udiskslinuxpartitiontable.c
The fourth parameter of bd_part_create() is 'size' not 'end'.
> Give libblockdev partition size not end

- src/udiskslinuxblock.c
The passphrase-path parameter is optional
> Don't include optional parameters in 'Missing parameter' message

- modules/lvm2/udiskslvm2moduleiface.c
- modules/lvm2/udiskslvmhelper.c
- src/main.c
- src/udisksdaemon.c
This fixes some of the `GLib-GObject-CRITICAL` messages that were being spewed when running the lvm dbus tests with storaged running.  A fairly large number of `GLib-GObject-WARNING` messages exist.
Note: core files created by:
``` bash
export G_DEBUG=fatal_criticals
```
To facilitate debug.  Ideally we should be running clean with
``` bash
export G_DEBUG=fatal_warnings
```
But there is much to fix before then.
> Some GLib-GObject-CRITICAL  fixes

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/targetcli_config.json
- src/tests/dbus-tests/test_60_partitioning.py
scsi_debug can create multiple SCSI devices, but all share the same backing
store (in RAM). Thus, they all contain the same data which causes serious issues
when used as PVs for LVM etc. Instead, let's use targetcli (LIO) which also allows us to
create fake SCSI devices, but each with it's own backing storage.
> Use targetcli instead of scsi_debug

- configure.ac
- modules/bcache/udiskslinuxmanagerbcache.c
- modules/btrfs/udiskslinuxfilesystembtrfs.c
- modules/btrfs/udiskslinuxmanagerbtrfs.c
- modules/zram/udiskslinuxblockzram.c
These changes allow storaged to build and run with libblockdev 2.0. Please note that the tests are doomed to fail now because the testers don't have libblockdev 2.0 installed (otherwise tests on the branches that don't have changes in this PR would fail).
> Adapt to libblockdev 2.0

- configure.ac
- modules/bcache/Makefile.am
- modules/bcache/udisksbcachemoduleiface.c
- modules/btrfs/Makefile.am
- modules/btrfs/udisksbtrfsmoduleiface.c
- modules/zram/Makefile.am
- modules/zram/udiskszrammoduleiface.c
- packaging/storaged.spec.in
- src/Makefile.am
- src/udisksdaemon.c
This intentionally  has changes from https://github.com/storaged-project/storaged/pull/128 merged because it builds on them. Please review only the last patch, the rest will be merged before this.
Also please note that this PR is for the *master-libblockdev* branch. I think we can leave the *master* branch as it is and only merge these changes there when *master-libblockdev* gets merged to master.
> Use libblockdev as a library not just the plugins

- src/tests/dbus-tests/test_mdraid.py
- src/udiskslinuxmanager.c
Added dbus tests for mdraid.
The second commit fixes creating arrays with name. When specifying array name using the `--name` option in mdadm (like `mdadm --create /dev/md127 --name "name" ...`) it will set name of the array but not name of the device so it for example doesn't create the `/dev/md/"name"` symlink etc. When creating the array using `mdadm --create "name" ...` (without specifying the `--name` option), mdadm will use the device basename for array name if needed.
> DBus tests for MDRaid and fix for creating raid with a name

- packaging/storaged.spec.in
Provides '/usr/lib/rpm/redhat/redhat-hardened-cc1' needed for build.
> Add 'redhat_rpm_config' to BuildRequires

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_loop.py
The goal of this PR is to provide missing tests for the ``Manager`` object/interface API. The ``MDRaidCreate`` method is covered by the PR with the MD RAID tests (https://github.com/storaged-project/storaged/pull/138). The ``Version`` property is covered by a test in *test_10_basic.py*. And since extra methods provided by modules should be tested in the modules' tests, the missing pieces here are:
Please ignore the commits up to "Merge pull request #1 from vojtechtrefny/master-tests_commons2" which are part of the PR with test improvements (https://github.com/storaged-project/storaged/pull/139), or ideally, review that PR. :)
> Tests for the Manager object/interface

- src/tests/dbus-tests/test_mdraid.py
When we start/stop the array, it takes a small amount of time for the change to
propagate to the DBus object's 'Running' property. This is not too great, but we
don't want this to make our tests failing in 9 of 10 runs.
> Give MD RAID some time to actually change its state

- src/tests/dbus-tests/safe_dbus.py
- src/tests/dbus-tests/test_job.py
'safe_dbus' module allows us to use dbus from multiple threads.
This part is copied from Anaconda installer codebase.
> Add dbus tests for job objects

- src/tests/dbus-tests/test_loop.py
So that there's some time for all the events to be processed, DBus objects
created, interfaces added,... Otherwise tests may randomly fail with stupid
errors.
> Always wait after loop device creation in tests

- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_drive_ata.py
We cannot use the LIO (targetcli) devices to perform tests of this interface
because it requires some "real" SATA/SCSI devices (but disk images attached to
VMs as SATA disks seem to work). Anyway, we cannot modify such devices we find
in the system so it's only possible for us to test the read-only properties and
methods. If no devices supporting the S.M.A.R.T technology are found, all the
tests are skipped.
> Test what we can from the Drives.Ata interface

- data/80-udisks2.rules
- data/udisks2.service.in
- src/tests/integration-test
- src/tests/test.c
- src/tests/test_polkitd.py
- src/udiskslinuxblock.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxfsinfo.c
- src/udiskslinuxpartition.c
- src/udiskslinuxprovider.c
- src/udisksmountmonitor.c
- src/udisksstate.c
- tools/umount-udisks.c
These are ports of the fixes/improvements included in the *udisks-2.1.8* release [1].
[1] https://lists.freedesktop.org/archives/devkit-devel/2016-November/001763.html
> udisks-2.1.8 ports

- doc/udisks2-sections.txt.in.in
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/test.c
- src/udisksdaemon.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxswapspace.c
- src/udisksspawnedjob.c
- src/udisksspawnedjob.h
The goal of this PR is to eliminate the issues caused by the [race condition when spawning processes](https://github.com/storaged-project/storaged/issues/147) which is causing our tests to fail quite often and which can cause severe issues in production. There are two things that should happen here:
``launch_spawned_job_sync()`` doesn't suffer from the race condition because it runs it's own main loop (in which signals are handled) after it connects the ``::completed`` signal. However, we can use it in all places where we spawn processes right now because none of the places has much to do after the processed is spawned (just some cleanup which can wait for the process to finish).
On the other hand, we still want to eliminate the race condition for future optimizations or development …
> Deal with the spawn race condition

- src/tests/dbus-tests/storagedtestcase.py
- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_90_swapspace.py
- src/tests/dbus-tests/test_drive_ata.py
- src/tests/dbus-tests/test_loop.py
- src/tests/dbus-tests/test_mdraid.py
It sometimes take few seconds to update content of properties
on dbus after some change. Instead of putting 'random' sleeps
in our tests, 'get_property' now returns an object and running
'assertEqual' on it will check value of the property multiple
times before raising an AssertionError.
> DBus tests: Use checks that automatically wait for property update

- data/80-udisks2.rules
They are not whitelisted by the rest of the rules, and it looks like
they don't get synthesized "change" events in any case.
> udev: Ignore ram block devices

- modules/bcache/udiskslinuxmanagerbcache.c
These are the last two compiler warnings we are getting, let's get rid of them. Ideally we should compile stuff with ``-Werror``, but there are some issues with this option in combination with ``-O0`` (added by ``--enable-debug`` option).  However, this is a step forward in that direction.
This fixes https://github.com/storaged-project/storaged/issues/118
> Get rid of the compiler warnings

- modules/bcache/data/org.freedesktop.UDisks2.bcache.policy.in
- modules/btrfs/data/org.freedesktop.UDisks2.btrfs.policy.in
- modules/zram/data/org.freedesktop.UDisks2.zram.policy.in
Action ids are case sensitive and we expect them to be lowercase.
> Fix PolicyKit action ids for bcache, btrfs and zram modules

- src/udiskslogging.c
Older versions don't support it.
Resolves: #159
> Only use structured logging with GLib >= 2.50

- modules/lsm/data/org.freedesktop.UDisks2.lsm.xml
Paragraphs in the documentation are preserved and converted into
<para>...</para> in the resulting generated docbook file. Thus if a newline
separates tag from its attributes, the result is an invalid XML file containing
things like this:
<link<para>....
Let's just don't be superstrict about number of characters on a line a get rid
of the extra newlines that cause these issues.
> Fix docs for the new LsmLocal interface

- modules/lsm/data/Makefile.am
- packaging/storaged.spec.in
Two fixes related the recent LSM changes -- new policy file needs to be included in the source archive and added to the `%files` section of the `storaged-lsm` package in the spec file.
> LSM packaging fixes

- configure.ac
Bcache functionality in the libblockdev-kbd plugin is now optional. If we were
using pkg-config, we would get proper cflags, but since we are using
libblockdev's plugins as standalone libraries, we need to do this on our
own. This makes sure the WITH_BD_BCACHE macro is defined which enables the
bcache functionality when building things with the libblockdev-kbd plugin.
> Build with libblockdev's bcache functionality enabled

- src/tests/dbus-tests/test_mdraid.py
The Delete() method takes care of stopping the array (if needed)
and stopping it explicitly before just creates a race condition
due to uevents handling.
> Do not stop the MD array before deletion in DBus tests

- src/tests/dbus-tests/test_mdraid.py
- src/tests/integration-test
It just makes our tests fail for no obvious reason. Probably something to do
with the new kernel+udev+mdadm in rawhide.
> Skip the MD RAID bitmap location test for now

- src/tests/dbus-tests/test_mdraid.py
- src/udiskslinuxmdraid.c
Changing bitmap location to 'none' doesn't trigger the change
uevent so we need to run the update function manually.
> Trigger update on the mdraid object after bitmap location change

- src/tests/dbus-tests/test_btrfs.py
The error message differs between versions of the btrfs-progs.
> Be less strict about the btrfs error for invalid RAID level

- po/POTFILES.in
Fixes "make check" error:
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.
modules/lsm/data/org.freedesktop.UDisks2.lsm.policy.in
Note that the .c files in lsm/ don't have any translations, so they don't need to be added.
> LSM: Add policy file to POTFILES.in

- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_btrfs.py
- src/tests/dbus-tests/test_job.py
- src/tests/dbus-tests/test_mdraid.py
With this option, lsblk will always print information just for
given device and for its children.
> DBus tests: Always use lsblk with -d (--nodeps) option

- src/udisksspawnedjob.c
This is a serious issue overlooked and introduced in the PR #189
(d66e8f3600421d0e3f83d195456693999ffe40f8).
> Fix how job->input_string_cursor is reset

- doc/man/Makefile.am
This fixes broken 'make dist' without LSM module enabled.
> Do not try to put LSM files in source archive without LSM support

- src/tests/dbus-tests/test_bcache.py
For some reason, they are failing in a very weird way. The libblockdev-bcache
tests are working just fine on the same machine/system so there must be
something wrong in the way storaged creates bcache. Definitely something worth
investigating, but right now we can just skip the tests so that we can run the
other ones properly even on i686.
> Skip bcache tests on 32bit Intel

- doc/udisks2-sections.txt.in.in
- src/tests/test.c
- src/udisksdaemon.c
- src/udisksdaemon.h
- src/udiskslinuxdriveata.c
- src/udiskslinuxswapspace.c
- src/udisksthreadedjob.c
- src/udisksthreadedjob.h
The former commit fixes a potential race condition when running threaded jobs. The latter one adds a function for running threaded jobs synchronously. Which is needed for replacing synchronous spawned jobs running utilities with threaded jobs running *libblockdev* functions.
note: **this PR is for the master-libblockdev branch**
> Fix and improvement for threaded jobs

- src/tests/dbus-tests/test_mdraid.py
- src/udiskslinuxmanager.c
Fix a bug when creating an mdraid array without specifying name (from #138) and a test for it.
> Fix creating mdraid without name

- src/tests/integration-test
scsi_debug devices are allocated/backed in RAM and for some reason (don't wanna
waste time on this) they can have very limitted size on the i686
architecture. But we don't need the device(s) to be 300 MB big for any test,
64 MB works just fine.
> Use smaller scsi_debug devices for integration tests

- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/udiskstestcase.py
They sometimes hang hard (in some syscall, cannot be killed). But if we disable
them, we can at least run all the other tests on a stable Fedora.
> Do not run MD RAID tests on Fedora 25

- data/org.freedesktop.UDisks2.xml
- doc/man/udisksctl.xml.in
- src/tests/integration-test
- src/udisksdaemon.c
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
- tools/udisksctl.c
Dear storaged folks,
I'm trying to add support for unlocking LUKS devices using binary data as was suggested for udisks [here](https://lists.freedesktop.org/archives/devkit-devel/2012-September/001315.html). There is also a corresponding [udisks ticket](https://bugs.freedesktop.org/show_bug.cgi?id=54828) where I tried to get in the patch.
I am now turning to you in the hope that storaged is more actively maintained and because I have seen talk about merging with udisks anyway.
Some more remarks:
I had to replace the `gchar* input_string` argument for the spawn/launch functions by a `GString` to make them work with binary data. For the `udisks_spawned_job_new` function, I simply changed the parameter type, since this function is used in only one place. For the …
> Support keyfiles

- configure.ac
- packaging/udisks2.spec.in
- src/Makefile.am
- src/tests/integration-test
- src/udisksdaemon.c
- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxencryptedhelpers.c
- src/udiskslinuxencryptedhelpers.h
- src/udisksstate.c
Please note that this PR builds on top of PR #194.
This needs three things to be done:
> Use libblockdev for LUKS operations

- src/udiskslinuxprovider.c
If not, return NULL indicating that it was not possible to get
the desired value by trimming it.
Fixes a potential issue introduced in
a09af2b322d82ea2c3228f3777e73e0142b73cdc.
> Only trim ".conf" from filename if it really has it

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
If given a passphrase explicitly, we should use it instead of trying to dig
something up from /etc/crypttab. If we are given no passphrase, we should report
an error. But since there's no way to pass None/NULL as a value for argument of
type "s" over DBus, we have to treat an empty string as no passphrase. However,
an empty string is a valid LUKS passphrase so we still need to provide a way to
pass it. This is now possible with the new 'keyfile_contents' optional argument
we just need to mention the trick in the documentation.
Please note that there's no change in behavior here because an empty string
passed as a value for the 'passphrase' argument hasn't (ever?) been working
before this change.
> Fallback to crypttab passphrase only if none given

- data/udisks2.service.in
Commit 52367c11f4edac673cf749d230707b04706395b2 removed the --no-debug flag from
org.freedesktop.UDisks2.service.in but udisks2.service still carries the --no-debug
flag and issues to following warning when started:
udisksd[2261]: The --no-debug option is deprecated and ignored. See '--help'.
> Remove the deprecated --no-debug from the udisks2.service file

- configure.ac
Without this using '--disable-fhs-media' actually results in
enabling fhs-media.
> Fix fhs-media configure option

- src/tests/dbus-tests/test_zram.py
Location of some sysfs attribute changed in recent kernels.
----
Tests will still fail because this -- https://github.com/rhinstaller/libblockdev/pull/177 -- fix for libblockdev needs to be merged first.
> DBus tests: Fix reading zRAM properties for tests

- src/tests/dbus-tests/force_clean.py
- src/tests/dbus-tests/run_tests.py
When tests finish force-clean script is now executed to remove any
devices that were not present before the tests started.
If script finds any device it logs that into syslog.
> Added after test cleanup

- src/udiskslinuxdriveata.c
'handle_smart_update' function already returns an error when
smart data update fails, no need to fill journal with warnings.
----
This fixes #177 but the original problem is somewhere in GNOME. It shouldn't try to update SMART data every 30 seconds if the call fails.
> Do not log warning for smart update errors

- packaging/udisks2.spec.in
Add libblockdev plugins needed by core Udisks (part, fs, swap, mdraid
and crypto) as Requires for udisks2 packages and move plugins needed
just by modules (btrfs, lvm and kbd) to propert udisks2 subpackages.
> Fix Requires and BuildRequires for libblockdev

- src/udisksata.c
- src/udisksdaemonutil.c
Couple of smaller fixes for duplicate code in `udiskstat.c` and `udiskdaemonutil.c`
Changes are based on `master-libblockdev` branch.  Changes tested with local `make ci`.
> Remove duplicate code in udisksata.c and udiskdaemonutil.c

- src/udiskslinuxfilesystem.c
HFS+ supports "uid" and "gid" options for mounting (similarly to
VFAT or NTFS), so we should use these when mounting on behalf of
a non-root user.
--------------
This fixes #211
Before:
```
$ cat /proc/mounts
/dev/sdc1 /run/media/vtrefny/untitled hfsplus rw,nosuid,nodev,relatime,umask=22,uid=0,gid=0,nls=utf8 0 0
```
```
$ ls -la /run/media/vtrefny/untitled
total 0
drwxr-xr-x. 1 root root  3 Apr 12 12:11 .
```
After:
```
$ cat /proc/mounts
/dev/sdc1 /run/media/vtrefny/untitled hfsplus rw,nosuid,nodev,relatime,umask=22,uid=1001,gid=1001,nls=utf8 0 0
```
```
$ ls -la /run/media/vtrefny/untitled
total 0
drwxr-xr-x. 1 vtrefny vtrefny  3 Apr 12 11:51 .
```
> Fix permissions when mounting HFS+

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxpartitiontable.c
We shouldn't allow to create logical partitions that start on the
extended partition metadata, but users have no way how to tell
how big the metadata are, so we want to fix the logical partition
for them.
> Move new partition start if overlaps with extended partition metadata

- src/udiskslinuxfilesystem.c
This should fix failing tests -- udev sometimes returns old
value when checking for label after "normal" uevents (triggered
by the change).
> Manually trigger uevent after changing filesystem label

- src/tests/dbus-tests/test_loop.py
It may take some short time and thus our tests may fail for no
real reason. Let's try to wait a second and then check if the
partitions were scanned or not.
> Give kernel a time to scan partitions on a loop device

- src/tests/dbus-tests/run_tests.py
- src/tests/integration-test
The root of all my local problems was caused because I was **missing the udev rules file**!  This PR adds code to copy that over too in the CI `run_tests.py` code.  It also adds code to remove the files that we copied over if no files existed before, so that we leave the system in the same state.  The actual unlink is commented out right now as the `intergration-test` doesn't do this copying.  I will work on moving this setup/teardown into a separate library so that we can share it across different tests cases.
Note: I also re-factored the copy code into one common function.
> Misc test fixes

- packaging/udisks2.spec.in
udevadm is now provided by 'systemd-udev', not by 'systemd'.
> Fix dependency for udevadm (#1424869)

- udisks/udisksclient.c
- udisks/udisksclient.h
We shouldn't emit the "change" signal for Job objects and some
progress related properties (e.g. "SyncRate" for MDRaid). This
signal is used by gvfs to check for device changes and emitting
this signal for "progress" changes (e.g. when running RAID check)
causes it to run checks for new devices or mountpoints every
100 ms during the check.
> Blacklist some changes for the UDisks.Client change signal (#1438232)

- doc/man/udisksd.xml.in
This option was removed in ce0b1e2f0b1bb486c7aafd1ae13c6cee00a32706
and we forgot to remove it from the manpage.
> Remove "--no-debug" option from udisksd manpage

- packaging/udisks2.spec.in
That's what Fedora packaging guidelines specify. [1][2]
[1] http://fedoraproject.org/wiki/Packaging:Systemd#Packaging
[2] https://fedoraproject.org/wiki/Packaging:Scriptlets?rd=Packaging:ScriptletSnippets#Systemd
> Use systemd-defined macros in the spec file template

- src/udisksdaemon.c
The newly created spawned and threade jobs are no longer being
started automatically since commits
fcc8bc3a7133cbea29e27a66b57ee4e158318335 and
d80ab581dfeb851747320fb4442a2655de1ea5bc. And a simple job has
nothing to start.
note: I noticed these when reviewing changes in PR #268
> Fix documentation of the daemon job launching functions

- configure.ac
If you do '--enable-lvm2' you stomp on the complier and linker flags.
I found this because I was unable to build a daemon with debug symbols
and all the modules enabled.
> configure.ac: Save/Restore compiler/linker flags

- configure.ac
- m4/ax_check_enable_debug.m4
So that we can run tests on RHEL/CentOS 7 and build *udisks2* for EPEL 7 in our copr repositories.
> Fixes needed to configure, compile and build on RHEL/CentOS 7

- packaging/udisks2.spec.in
udisks2-zram package is only on Fedora
> Run post actions for udisks2-zram package only on Fedora

- packaging/udisks2.spec.in
There's no 'udev' package in recent Fedora and RHEL/CentOS
distributions, but 'udev' is correctly provided by the packages
providing the udev-related tools -- 'systemd-udev' on Fedora and
'systemd' on RHEL/CentOS.
> Require 'udev' not 'systemd-udev'

- modules/zram/udiskslinuxmanagerzram.c
- src/udiskslinuxmanager.c
"‘g_free’ discards ‘const’ qualifier" in "handle_loop_setup"
"comparison between signed and unsigned integer" in zram module
> Fix two gcc warnings

- modules/bcache/data/org.freedesktop.UDisks2.bcache.xml
- modules/btrfs/data/org.freedesktop.UDisks2.btrfs.xml
- modules/zram/data/org.freedesktop.UDisks2.zram.xml
We changed a few things from the modules' APIs. Nobody's probably
using these methods and properties, but we should explicitly
mention they changed in this new version.
> Inform about changes in version 2.7.0 in the documentation

- configure.ac
When using --enable-available-modules, the configure script fails at the first two AC_MSG_ERROR calls when LibStorageMgmt support is not present. The checks later wasn't yet executed at that time. This simple change makes it work as expected.
> Don't always fail on missing LibStorageMgmt support

- src/udiskslinuxdriveobject.c
HighPoint RAID disks have the same serial. (#290)
> Don't use serial as unique ID for drive objects

- udisks/udisksclient.c
The value returned from g_strcmp0() is not a boolean. And a
GVariantIter has to be initialized before use.
> Fix how UDisksClient filters property changes

- udisks/udisksclient.c
"changed_blacklist" table is a class member and we really don't
want to destroy it when destroying one instance of the UDisksClient.
> UDisksClient: Do not try remove changed_blacklist hash table in finalize

- src/udiskssimplejob.c
The API states that passing NULL is acceptable, but when done we end up
down a path which causes an assertion which will trigger an abort if
G_DEBUG=fatal-criticals is enabled.  Pass an empty message when message is
NULL to avoid this.  Numerous other code paths are already calling this
function with message == "".
> udiskssimplejob.c: Allow NULL for message

- configure.ac
This fixes #314 along with some similar problems found in configure.ac.
Some of the header file checks for libblockdev were incorrect
(included without the leading blockdev/ directory, even though
in the udisks sources they are included correctly). So there were
some incorrect workarounds to add -I/usr/include/blockdev for
those header file checks.
This fixes the configure.ac to remove the hardcoded -I/usr/include/blockdev
include paths and just check the correct header files instead.
> configure.ac: Fix references to /usr prefix

- src/udiskslinuxdriveobject.c
This fixes a bug in multipath drives detection in Cockpit tests
introduced by 1d07929b277f9f15db9e5f273ef8f7ac67129a9f
Usinf both model and serial of the disks should be unique for
HighPoint RAID drives and same for multipath devices.
> Use "model_serial" as unique ID for drive objects

- modules/lvm2/jobhelpers.c
LVM now asks for confirmation when trying to resize mounted
filesystems. (Some filesystems like ext4 must be unmounted when
shrinking.) With older version of LVM, the "--yes" option wasn't
needed.
> Add "--yes" arg when resizing filesystem with "lvresize"

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxpartitiontable.c
Not sure if I like this implementation since theoretically the partition type can always be guessed correctly except if the partition type should be extended. (Note that doing so would alter existing behavior and therefore break applications that rely on the current behavior.)
Deriving "extended" from the filesystem partition seems legit and is already done by udisks.
Note that on my end the `test_fill_with_primary_partitions` fails after adding the second partition due to this error: 
> Error waiting for partition to appear: Timed out waiting for object
I've got no clue why that happens. Help wanted.
---
Implement feature requested in #318.
Allow the user to specify the "partition-type" option in
"CreatePartition" to explicitly specify whether the partition should be
a primary, extended …
> Allow the user to specify the partition type

- data/org.freedesktop.UDisks2.xml
The usage of libblockdev brought 0 as valid value for
size in PartitionTable.CreatePartition which chooses
the maximal partition size.
Also libblockdev will not create the partition in front of the offset.
> Document behavior of PartitionTable.CreatePartition

- src/udiskslinuxpartition.c
Since 089c06e5823e009b962c642ef12a97e174a46a4e
there were no authorization checks for partition
objects, so anyone could delete them.
> Fix broken partition authorization code

- data/org.freedesktop.UDisks2.xml
- packaging/udisks2.spec
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
- udisks/udisksclient.c
The Filesystem interface now has a resize method
that checks if the action is safe during mount.
It also supports resizing to maximum.
The progress parsing of the utility still missing.
Hello,
this is how I would like to do the final interface.
The progress property of the job is not yet populated because this needs some work in libblockdev, but that is mostly only relevant for shrinking operations which need to move data.
Depends on https://github.com/storaged-project/libblockdev/pull/217
> Add Filesystem Resize, Check, Repair

- data/org.freedesktop.UDisks2.xml
I/O needs to be block-aligned because of the `O_DIRECT` flag. There was no
reason for page-alignment found.
Reference: [`0139855`](https://github.com/storaged-project/udisks/commit/0139855348ae204311b12b0d80c48d98a6bc9d51#commitcomment-22860904).
> Correct alignment specified in the docs

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_10_basic.py
- src/udiskslinuxmanager.c
The availibility of creation, resize, check and repair utility
for a filesystem can be queried through new methods CanFormat,
CanResize, CanCheck and CanRepair in org.freedesktop.UDisks2.Manager
which is useful for UIs.
It makes use of the functions in PR https://github.com/rhinstaller/libblockdev/pull/217
and so is not ready for merging. But it would be nice to know if this makes sense. In general the semantics are to return an error if an action is not supported and return false if only the binary is missing.
> Query methods for available utility binaries

- data/80-udisks2.rules
Partitions created using 32bit isohybrid images have a wrong
partition type (0x17 instead of 0x00) and we need to stop ignoring
these too.
> Fix detection of drives created using isohybrid images (#1437791)

- src/tests/integration-test
Expected error is different when using new error codes and messages
from libmount >= 2.30
> Integration test: Fix error message for mounting RO devices

- data/80-udisks2.rules
The virtual CD is/may be a whole block device with a partition
table which has ID_PART_TABLE_TYPE instead of
ID_PART_ENTRY_SCHEME.
Resolves: #344
> Try more to ignore WD SmartWare virtual CDs

- src/tests/dbus-tests/run_tests.py
When dbus tests are run, journal output is logged and saved.
> Added journal dumping into dbus tests

- src/tests/dbus-tests/test_loop.py
- src/udiskslinuxmanager.c
This commit adds back calling "udisks_state_add_loop" method after
creating the loop device. This was accidentally removed when
rewriting the loop code to use libblockdev.
Fixes #356
> Fix setting "SetupByUID" property when adding a new loop device

- data/org.freedesktop.UDisks2.policy.in
- data/org.freedesktop.UDisks2.xml
- src/Makefile.am
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxblock.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxfilesystemhelpers.c
- src/udiskslinuxfilesystemhelpers.h
We already allow taking ownership when creating a filesystem
(basically running chown on the filesystem root after creating it)
but it could be useful to have this functionality for existing
filesystems too because right now it isn't possible to write to
devices with filesystems created using different tools and it isn't
user friendly to run chmod/chown manually.
> Add a function to "take ownership" of a filesystem

- src/tests/dbus-tests/test_zram.py
Loading and unloading the 'zram' module causes kernel panics on
rawhide kernels.
> Disable ZRAM tests on Rawhide

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxblock.c
- src/udiskslinuxfsinfo.c
As described in #338, 'mkudffs' is supposed be run in a different
way to actually create a modern UDF file system with all the
desired parameters.
Among the other things, older versions of 'mkudffs' are not able
to determine the device's block size so we need to do it on our
own which requires some extra effort.
Resolves: #338
> Fix how we create UDF file systems

- src/tests/dbus-tests/test_bcache.py
They just keep failing randomly due to some issue(s) in udev
and/or kernel. We can do nothing about it.
> Skip bcache tests everywhere

- src/tests/dbus-tests/run_tests.py
It's causing issues because importing blivet in the cleanup code
makes the system udisks daemon autostart while the cleanup
removes devices wildly which causes the daemon to segfault.
> Disable cleaning using blivet for now

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxblock.c
These ids will be used when formatting partition with
"update-partition-type" option set to True.
Fixes #377
> Set corrent part type/id and GUID for UDF formatted partitions

- data/80-udisks2.rules
- src/udiskslinuxfilesystem.c
Fix for three bugs from freedesktop bugzilla.
> Few small fixes

- src/udiskslinuxfilesystem.c
The "lazy" option should be used for force unmounting local
filesystems. "force" option works only with NFS. (See umount man
page, options "-l" and "-f".)
Fixes #393
> Fix force unmounting

- tools/udisksctl.c
When trying to complete the command we have to check the current
argument too, not just the previous one to make sure completion
works also with "udisksctl mount --object-path[tab]".
Resolves https://bugs.freedesktop.org/show_bug.cgi?id=95404
------
When trying to complete "udisksctl mount --object-path" `completion_prev` is `mount` and `completion_cur` is `--object-path` so the original if doesn't work here.
Btw. there is a quite a lot of code duplication in `udisksctl.c` we should get rid of but this is out of scope for this PR.
> Fix bash completion for udisksctl

- doc/Makefile.am
New gtk-doc 2.16 for some reason automatically creates a no-op
"$(DOC_MAIN_SGML_FILE)" make target that overrides our target
for creating "udisks2-docs.xml", "udisks2.types" and
"udisks2-sections.txt" files.
> Fix building documentation with new gtk-doc

- modules/iscsi/Makefile.am
- modules/iscsi/udisksiscsidbusutil.c
- modules/iscsi/udisksiscsidbusutil.h
- modules/iscsi/udiskslinuxmanageriscsiinitiator.c
- src/tests/dbus-tests/test_30_iscsi.py
Login and Logout methods now wait for the device and session
objects to be added to (removed from) DBus.
Fixes #342
> Make iSCSI Login and Logout wait for DBus objects update

- src/udisksdaemon.c
Unless somebody tries to do something that actually requires the
plugin, it's not really needed. And if they do, they will get an
error like any other.
The next step is to be able to react dynamically on the
availability of the required tools/libraries/etc. But we need a
better support for that in libblockdev in the first place.
> Start even if a libblockdev plugin fails to load

- src/udiskslinuxblock.c
"label" is used for the dry run so we need to get it earlier.
> Move label option lookup at the start of handle_format

- src/tests/dbus-tests/test_60_partitioning.py
SetFlags expects "normal" decimal number not binary.
> Fix SetFlags call in partitioning test

- src/udiskslinuxmanager.c
GNOME (gfvs) automatically mounts only loop devices created by
user. It uses the 'SetupByUID' property but it doesn't react if
the property is changed later. We need to make sure 'SetupByUID'
is right when the loop object is created -- we need to create
our state file earlier.
--------
Fixes #356
This is not an ideal solution for this issue. GNOME/gvfs should really check the loop device after property change and automount it.
> Fix loop device automounting in GNOME

- src/udiskslinuxblock.c
So that errors from cryptsetup will be reported back to the caller,
even when "non-block" is set.
A better alternative would be to do a dry-run of "cryptsetup
luksFormat", but I don't think that's possible.
> Run cryptsetup before returning from non-blocking Format

- data/Makefile.am
- data/clean-mount-point@.service
- packaging/udisks2.spec
- src/Makefile.am
- src/udiskslinuxfilesystem.c
When udisks2 is used for mounting devices, it may need to create
the mount point directory. If unmount happens later, udisks2
cleans after itself and removes the mount point
directory. However, if the unmount happens during reboot, the
udisks2 daemon may already be terminated not having a chance to
do the cleanup. We need a different mechanism to do the job in
such cases.
systemd provides us with such a mechanism so let's make use of
it.
Resolves: rhbz#1384796
> Add and use a service for cleaning up mount point directories

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxpartition.c
This fixes a regression.
The documentation for the "Flags" property says that GPT bit 2 (Legacy BIOS
Bootable) is supported, and indeed it used to be the case (e.g. it works with
2.1.8-1 on Debian Stretch). But the code does not support it anymore as of
2.7.3-4 on current Debian sid.
This commit depends on BD_PART_FLAG_GPT_LEGACY_BOOT in libblockdev:
* issue: https://github.com/storaged-project/libblockdev/issues/287
* pull request: https://github.com/storaged-project/libblockdev/pull/288
Fixes: #415
> Re-add support the legacy BIOS bootable GPT flag

- data/Makefile.am
clean-mount-point@.service is not created from a template and
thus should not be removed.
> Do not clean all .service files

- src/udiskslinuxpartitiontable.c
By using table_get_type_() we get a pointer to the property which
may change between being tested for one of the supported values
and later being actually used to determine what to do based on
its value. That may cause various failures, including
segmentation faults.
A particular example is when working with a GPT partition table
where the udev-blkid machinery can tell us that there's a "gpt"
partition table, but later change it to "PMBR" (maybe
temporarily) while the thread handling the
handle_create_partition() function is midway.
> Make sure the table_type is consistent in handle_create_partition

- src/tests/integration-test
And also don't try to run the tests if we fail to detect the
distribution and/or version.
Resolves: rhbz#1508385
> Fix checking for distribution and version in integration tests

- README.md
It's no longer such a total shame.
> Display the CI status on the main GH page

- src/tests/dbus-tests/test_60_partitioning.py
Looks like 1 second is quite often not enough. Also, we need udev
to do its job first.
> Try to wait a bit longer before retrying to remove a partition

- src/tests/dbus-tests/test_60_partitioning.py
There are two classes inherited from TestCase in the partitioning
DBus tests. We need to use the same trick when trying to remove a
partition in both places.
> Use the same trick when removing partition in both TestCases

- udisks/udisksobjectinfo.c
udisks_client_get_object_info calls increase memory usages of gvfs-udisks2-volume-monitor, let's fix that.
> UDisksObjectInfo: Fix size_str memory leaks

- src/tests/integration-test
This actually doesn't solve the issue with polkit tests failing,
but we need them to at least fail and not just hang forever.
> integration-test: Do not wait forever in polkit tests

- src/tests/integration-test
We need to wait until the 'mountpoints' property is updated and
'self.assertProperty' does that.
> integration-test: Fix checking for mountpoints after removing luks

- data/org.freedesktop.UDisks2.xml
- src/tests/integration-test
- src/udiskslinuxblock.c
- src/udiskslinuxfsinfo.c
- src/udiskslinuxfsinfo.h
It unfortunately seems to be necessary to use this option in certain
situations.  See https://bugzilla.redhat.com/show_bug.cgi?id=1516041
for example.
> Add 'no-discard' option to formatting methods

- src/tests/integration-test
The scsi_debug module doesn't seem to be causing kernel panics
anymore.
> Do not skip integration tests on CentOS/RHEL

- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/udiskstestcase.py
- src/udiskslinuxfilesystem.c
The first patch is just a cosmetic change. The second patch makes sure the same mount option is not specified multiple times which could lead to hard-to-define/undefined results (which value wins?). By using defaults first and then possibly overriding them with user-specified values, we make sure the latter win.
The third patch implements what has been requested in #413 -- using better values for ``mode`` and ``dmode`` mount options if a file system using these is mounted at a shared location. Please see the commit for details.
> Use different options for file systems mounted at shared locations

- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/udiskstestcase.py
The mount point cleanup is done asynchronously so there's no
guarantee that the mount point from the previous test is going to
be cleaned up when some test is running. And if not, a new one
with a number suffix will be created. Which is totally fine and
expected, but we need to take that into account in the checks.
> Only check mount point prefix in the iso9660 tests

- src/tests/integration-test
For some reason the tests quite often end up just hanging in some
uninterrupted state on Fedora 26.
> Skip PolicyKit integration tests on Fedora 26

- modules/lvm2/udiskslinuxvolumegroupobject.c
Once the whole internal name has matched, the other name must also be
at the end.  Otherwise we might find "lvol0" when looking for
"lvol0_meta", for example.
The symptom is that the size of a pool is reported as twice its data
size, instead of data plus metadata size, which funnily is exactly the
same symptom fixed by 043edcb.  Deja vu...
> lvm2: Don't match prefixes in cmp_int_lv_name

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
This allows the client to detect filesystems that could be resized to
fill more of their block device.
> core: Add o.fd.U.Filesystem.Size property

- src/udiskslinuxfilesystem.c
We need to use the 'systemd-escape' command -- it escapes more
symbols and manually escaping only slashes isn't enough.
> Fix escaping mountpoint for the cleanup service

- configure.ac
- data/org.freedesktop.UDisks2.xml
- doc/udisks2-docs.xml.in.in
- doc/udisks2-sections.txt.in.in
- doc/uml/classes.txt
- packaging/udisks2.spec
- src/Makefile.am
- src/tests/dbus-tests/test_80_filesystem.py
- src/udisksdaemon.c
- src/udisksdaemon.h
- src/udisksdaemontypes.h
- src/udiskslinuxblock.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxprovider.c
- src/udisksprivate.h
- src/udisksthreadedjob.c
- src/udisksutabentry.c
- src/udisksutabentry.h
- src/udisksutabmonitor.c
- src/udisksutabmonitor.h
Export the info stored in /run/mounts/utab using the org.freedesktop.UDisks2.Block.Configuration property. For the moment the code to get the mount user options (x-...) has not been moved to libblockdev. I suggest to do that in a later branch as at this point other things need to moved.
> Add utab monitor

- src/tests/dbus-tests/run_tests.py
Writing the journalctl output from tests may fail from several
reasons. Just ignore the exceptions without crushing the test
suite.
> Ignore errors when saving journal output in tests

- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
Together with [changes in libblockdev](https://github.com/storaged-project/libblockdev/pull/316) this adds support for (un)locking LUKS2 devices using udisks.
> LUKS2 unlocking support

- src/tests/integration-test
Try give udisks more time to recognize new filesystem on the CD
after the scsi debug device format change.
----
This should fix failing tests on CentOS 7. Running `udev settle` twice is apparently not enough after triggering the udev change event for the CD.
> integration-test: Wait longer after the scsi debug CD format

- src/tests/integration-test
Using Python bytes doesn't work on newest GLib/pygobject.
-----
Pygobject issue: https://gitlab.gnome.org/GNOME/pygobject/issues/174
> Fix creating GVariant byte array in integration tests

- src/udiskslinuxfilesystemhelpers.c
We create only "/run/udisks2" directory without the localstate
directory prefix, so we shouldn't use it.
Fixes #504
> Fix directory we use for temporary mounts

- src/tests/integration-test
The cpe name which is used to guess the distro is optional and not available on e.g Ubuntu. The returned value is currently only used to skip some problematic test on fedora 26, returning a default name/version on errors should lead to the same behaviour without erroring out on other distributions.
> integration-test: don't error out on an unknown distro

- data/Makefile.am
| sed: can't read udisks2.service.in: No such file or directory
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
> data: fix out of tree build

- src/udisksstate.c
It needs to return TRUE if the conditions are met.
Thanks F-i-f at GitHub for reporting this and providing a patch!
Fixes: GH-519
> Fix _udisks_state_has_loop_list_visitor()

- src/udisksdaemon.c
- src/udiskslinuxblock.c
- src/udiskslinuxdriveata.c
- udisks/udisksclient.c
- udisks/udisksclient.h
Fixes https://github.com/storaged-project/udisks/issues/516
Only the format and secure erase jobs were
covered with a systemd logind inhibitor
to prevent automatic or user-triggered suspend.
Move the inhibitor management to the job construction
and deconstruction code.
> Register system inhibitor for all jobs

- src/tests/integration-test
If the integration tests are run from a different directory, we will
fail to find targetcli_config.json with an error like
```
======================================================================
ERROR: setUpClass (__main__.MDRaid)
----------------------------------------------------------------------
Traceback (most recent call last):
File "src/tests/integration-test", line 1795, in setUpClass
cls.devices = setup_lio()
File "src/tests/integration-test", line 1725, in setup_lio
assert len(vdevs) >= 4
AssertionError
```
let's calculate the absolute path relative to the integration-test
executable itself.
The problem was initially debugged and fixed in Ubuntu by Sebastien
Bacher (@seb128), with many thanks.
> tests: Pass absolute path to targetcli_config.json

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
Reverts storaged-project/udisks#525 which should have not been merged by @japokorn without fixes applied and without ACK.
> Revert "New property for LUKS metadata size"

- udisks/udisksclient.c
This adds the partition type (confirmed on Macbook Pro with Fedora 28 here) for Apple APFS partitions. It does not add any way to get the filesystem type though. I am not sure how to do that, or even if it is possible without adding APFS support to the kernel. I am not sure if there is an example of a filesystem that it would be useful to get information on but which is currently unsupported.
If there is anything I can do to add the apfs filesystem identification too then please point me in the direction. 'file' does support the magic at the beginning of the partition so it should be possible.
> Add Apple APFS gpt partition type

- src/udisksdaemon.c
- src/udisksdaemon.h
- src/udiskslinuxfilesystem.c
If the libblockdev functions for FS check, repair or
resize support progress reporting, the Progress
property of a UDisksJob is set up and updated on
each report of the progress function.
The current job which is to be updated is managed
per thread and the progress function is also only
set up in libblockdev for the current thread.
The local progress report spans only the invokation
of the single libblockdev operation that the DBus
method handler calls in its dedicated thread.
Requires merging of https://github.com/storaged-project/libblockdev/pull/353
> Set Job Progress property for FS check, repair, resize

- modules/lvm2/jobhelpers.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
- modules/lvm2/udiskslvm2moduleiface.c
Two small fixes for LVM plugin. I discovered the problem when both `bd_lvm_vgs` and `bd_lvm_pvs` failed and because both functions use the same GError udisks complained about overwriting it.
```
GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Failed to fork (Cannot allocate memory)
```
We also use only the message from these errors in a warning, so we need to clear the error too.
>  Return from 'vg_task_func' if 'bd_lvm_vgs' failed

- src/tests/dbus-tests/udiskstestcase.py
monotnonic package is not available on some systems because on
Python 3.3 or newer it is only an alias for 'time.monotonic'
from the standard library.
> udiskstestcase.py: Use 'monotic' from 'time' on python >= 3.3

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
- src/udiskslinuxblockobject.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxprovider.c
New 'CleartextDevice' property for the 'Encrypted' interface.
Fixes #456
> Add a property with the cleartext device path for unlockdev LUKS

- src/udiskslinuxencrypted.c
Unlocking TCRYPT volumes can take a lot longer than unlocking LUKS
volumes, so the 10 second timeout is not enough in some cases.
> Increase timeout for waiting for cleartext object after unlocking

- src/tests/integration-test
Fixes: #517
This also fixes another issues in the tests -- we are not waiting long enough after manually creating the array. The "wait asserts" in integration tests are not really good, I'd like to copy the code we have in dbus tests but that is a quite big change for this fix.
> Skip mdraid tests on s390

- configure.ac
This is also checked inside the enable_man conditional.  Remove this
redundant check so that we don't require xsltproc when --disable-man is
specified.
> configure: remove redundant xsltproc check

- data/80-udisks2.rules
As we worked out in
https://bugzilla.redhat.com/show_bug.cgi?id=1628774 , with
multipath-tools 0.7.7 or higher, DM_MULTIPATH_DEVICE_PATH gets
set to the value 0 for non-multipath devices in some cases.
Before 0.7.7, it was always either set to 1 or not set at all.
Now it can be set to 0, checks like this:
ENV{DM_MULTIPATH_DEVICE_PATH}=="?*"
don't work right any more, because that check will actually
match if the value is 0 (it will only not match if the var is
not set at all, or is set to an empty string). Instead we should
just check if it is set to exactly 1, otherwise assume the device
isn't multipath.
The impact of this is I think quite limited: we only skip two
rules if this check matches, and they only affect mdraid devices.
On installed systems without any multipath devices, the …
> Fix DM_MULTIPATH_DEVICE_PATH in udev rules

- src/udiskslogging.c
If the message in g_log_structured itself
contained format sequences like %d or %n they
were applied again, leading to leaked stack contents
and possibly memory corruption. It can be triggered
e.g. by a volume label containing format sequences.
Print the message argument itself into a "%s" string
to avoid intepreting format sequences.
https://github.com/storaged-project/udisks/issues/578
> Fix string format vulnerability

- src/tests/dbus-tests/test_60_partitioning.py
- src/udiskslinuxblockobject.c
- src/udiskslinuxpartition.c
We are currently updating the "Partitions" property of the
"PartitionTable" interface only as a result of a change event on
the disk. This works when actually creating the partition but not
when "adding" a disk that already has partitions (e.g. plugging in
a USB flash drive). This adds a special update call when handling
the "add" event for a new partition.
Fixes: #570
> Update the Partitions property on partition "add" event

- udisks/udisksclient.h
- udisks/udisksobjectinfo.c
- udisks/udisksobjectinfo.h
Builds on https://github.com/storaged-project/udisks/pull/492 for some of the manually-defined types. I also added a GType macro and fixed a typo.
Unfortunately, UDisksObject (which is part of the generated code) still doesn't have autocleanup support. I'm not sure why: I think it's probably a gdbus-codegen bug. (**Update**: [it is](https://gitlab.gnome.org/GNOME/glib/merge_requests/420).)
> Add g_autoptr() for Client, PartitionTypeInfo, ObjectInfo

- src/udiskslogging.c
The call to `g_log_structured()` was not conforming the rules stated in the
documentation: "The MESSAGE-format pair has to be the last of the key-value
pairs, and MESSAGE is the only field for which printf()-style formatting
is supported."
> udiskslogging: Fix THREAD_ID field logging

- data/Makefile.am
- packaging/udisks2.spec
To better support stateless systems with an empty /etc, the old location
in /etc/dbus-1/system.d/ should only be used for local admin changes.
Package provided D-Bus policy files are supposed to be installed in
/usr/share/dbus-1/system.d/.
This is supported since dbus 1.9.18.
https://lists.freedesktop.org/archives/dbus/2015-July/016746.html
> Move D-Bus policy file to /usr/share/dbus-1/system.d/

- doc/man/udisksctl.xml.in
Added short description for the "device" options (--object-path
and --block-device) and for options for specific commands.
Resolves: rhbz#1568269
-----
We already have some short descriptions for the options in `udisksctl.c` so I mostly copy-pasted these or used man pages for the commands we use (`mount`, `losetup`, etc.).
Compiled version of the man page: https://vtrefny.fedorapeople.org/misc/udisksctl.1
> man: Describe command options in the udisksctl man page

- src/udiskslinuxblock.c
Previously, if `O_RDWR | O_RDONLY | O_WRONLY` were specified, the error
message would include whitespace up to the indentation level between its
two sentences. This is harmless but ugly.
(I notice that, since `O_RDONLY == 0`, `flags & O_RDONLY` is always false…)
> block: remove extra whitespace in OpenDevice error message

- tools/udisksctl.c
Some pagers freeze when fetching data making it impossible to quit or
scroll through already buffered lines. Let's explicitly close stdout so
that pagers are aware that no more data are coming.
> udisksctl: Explicitly close stdout once dump command finishes

- src/tests/dbus-tests/test_80_filesystem.py
ISO9660	format creation is done outside of udisks and while we let udev
to settle it still takes a moment for udisks to finish probing the new
filesystem. As a result occassional test failures were observed as a timing
issue.
> tests: Sleep for a while after ISO9660 image creation and udev settle

- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
The udisks_linux_block_object_get_device() call takes reference to UDisksLinuxDevice
and users are supposed to free it after use.
--
This was a blind shot, incidentally found by reading the code. No idea about the consequences as this may reveal wrong reference ownership somewhere else in the code.
Btw. the `find_fstab_entries_for_device()` function within `udiskslinuxblock.c` looks pretty nasty with the use of `goto` instead of proper `continue`. Also the `UDisksLinuxDevice->udev_device` is never supposed to be _NULL_ unless I'm missing something, not sure what was the original idea for this test here.
> Fix leaking UDisksLinuxDevice

- modules/lvm2/udiskslinuxlogicalvolume.c
Otherwise lvsnapshot_create_job_func will get a random value instead
of zero for snapshots of thin volumes and will do the wrong thing.
> lvm2: Always initialize data.new_lv_size in CreateSnapshot

- src/udiskslinuxfilesystem.c
I don't have the full theory for why this is necessary, but I can see failures without this in the Cockpit integration tests.
What seems to happen is that resize2fs opens and closes the block device twice, which normally generates two "change" events.  Thus, UDisks2 runs dumpe2fs twice: once too early (which might give the old size, or the new size, or even fail with a superblock checksum mismatch), and then again after the resize is done (which gives the correct size).
However, sometimes processing for the first event is still ongoing when the second event should happen, and the second event is dropped.
> udiskslinuxfilesystem: Trigger uevent after resize

- src/tests/integration-test
On Ubuntu ppc64el, the integration tests are almost always failing like
this:
Traceback (most recent call last):
File "src/tests/integration-test", line 1788, in test_md_raid_methods
self.assertNotProperty(block_interface, 'mdraid-member', '/')
File "src/tests/integration-test", line 542, in assertNotProperty
self.assertNotEqual(obj.get_property(name), value)
AssertionError: '/' == '/'
Upon investigation, it turns out that this is due to a race condition in
the tests - when we use targetcli to create the devices, they are not
seen by udev immediately, and consequently are not visible to udisks
either. If an array is created in this period, this causes the
MDRaidMember property to not be set. We can fix this problem by calling
`sync()` before running any tests, to ensure that our devices …
> integration-test: Sync after creating our fake devices

- modules/lvm2/udiskslinuxlogicalvolume.c
- modules/lvm2/udiskslinuxmanagerlvm2.c
- modules/lvm2/udiskslinuxvolumegroup.c
- modules/vdo/udiskslinuxblockvdo.c
- modules/vdo/udiskslinuxmanagervdo.c
- src/udisksbasejob.c
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxblock.c
- src/udiskslinuxdrive.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxloop.c
- src/udiskslinuxmanager.c
- src/udiskslinuxmdraid.c
- src/udiskslinuxpartition.c
- src/udiskslinuxpartitiontable.c
- src/udiskslinuxswapspace.c
Previously, the function was lying. It didn't return the actual group of
the caller, but the default group associated with the user configured in
/etc/passwd (or equivalents).
I first wanted to change the function to return the gid of the caller. The problem there is that glib doesn't provide any way to do that - one can get a [`GCredentials`](https://developer.gnome.org/gio/stable/GCredentials.html) for the caller through a long chain of function calls, but this doesn't actually contain a group id, except through the platform-dependent return value of `get_native`.
I don't believe there's any problem with using the gid configured in passwd instead of the caller for the file system permissions like the current code does, but since this was a generic utility function that might (or might …
> split out get_user_info from get_caller_uid_sync

- .gitignore
- autogen.sh
- configure.ac
- data/Makefile.am
- data/org.freedesktop.UDisks2.policy.in
- modules/bcache/data/Makefile.am
- modules/bcache/data/org.freedesktop.UDisks2.bcache.policy.in
- modules/btrfs/data/Makefile.am
- modules/btrfs/data/org.freedesktop.UDisks2.btrfs.policy.in
- modules/iscsi/data/Makefile.am
- modules/iscsi/data/org.freedesktop.UDisks2.iscsi.policy.in
- modules/lsm/data/Makefile.am
- modules/lsm/data/org.freedesktop.UDisks2.lsm.policy.in
- modules/lvm2/data/Makefile.am
- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.policy.in
- modules/vdo/data/Makefile.am
- modules/vdo/data/org.freedesktop.UDisks2.vdo.policy.in
- modules/zram/data/Makefile.am
- modules/zram/data/org.freedesktop.UDisks2.zram.policy.in
- packaging/udisks2.spec
- po/Makevars
- po/POTFILES.in
This patch changes the build scripts to use `gettext` for i18n strings extraction and merging in place of `intltool`. This allow dropping the dependency on outdated intltool. It also drops the `gnome-common` dependency, now deprecated.
https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration
https://wiki.gnome.org/Projects/GnomeCommon/Migration
Closes https://github.com/storaged-project/udisks/issues/629
> build: Migrate from intltool to gettext

- packaging/udisks2.spec
References: https://fedoraproject.org/wiki/Changes/Remove_Group_Tag
(changes ported from Fedora)
> packaging: Remove obsolete Group tag

- configure.ac
- data/Makefile.am
- data/tmpfiles.d/Makefile.am
- data/tmpfiles.d/udisks2.conf
- packaging/udisks2.spec
Currently, when udisks is configured to use /run/media instead of
/media, on most operating systems, the /run/media directory is created
by udisks itself when the first mount is handled. This causes problems
when creating rootless or unprivileged OCI containers that are meant
to have access to udisks mount points because, depending on whether
something has been mounted or not after the current boot, /run/media
might be absent.
A rootless or unprivileged OCI container is created, by definition,
without requiring root privileges. Therefore, it's not possible to
create /run/media during container creation because creating a
directory under /run can only be done by the root user, and a missing
directory can't be bind mounted into the container. Moreover OCI
containers tend to be immutable, so …
> Install a tmpfiles.d snippet to create /run/media on boot with systemd

- modules/iscsi/data/org.freedesktop.UDisks2.iscsi.xml
- modules/iscsi/udiskslinuxmanageriscsiinitiator.c
- src/tests/dbus-tests/test_30_iscsi.py
Initiator name can contain some non-unicode characters so we need
a function to get it as bytes.
> Add function to get iSCSI initiator name as a byte array

- src/tests/dbus-tests/run_tests.py
- src/tests/integration-test
When working on #646 I have noticed that we don't remove config files installed for tests. This PR enables the config files cleanup for both DBus tests and integration tests.
> Various test cleanup related fixes

- src/udiskslinuxfilesystem.c
Filesystem.Resize waits for size to be updated
Clients testing the size property after a resize
may run into a race where the Filesystem.size property
was not yet updated but Filesystem.Resize had
already returned.
Add a waiter to check whether the size property
got updated to the new value as present on the
disk. This is only done if there initially was
a valid size property.
Factor out common code for querying the
filesystem size.
Closes: https://github.com/storaged-project/udisks/issues/572
> Filesystem.Resize waits for size to be updated

- src/tests/dbus-tests/run_tests.py
- src/tests/integration-test
We need to make sure that /etc/udisks2 exists if we want to copy
our config file to it.
Missed this in #651
> tests: Create udisks2 conf directory if it doesn't exist

- src/tests/dbus-tests/test_50_block.py
- src/udiskscrypttabmonitor.c
There can be multiple spaces in the crypttab and g_strsplit_set can't handle it. Fortunately strtok can be easily  used to split string to tokens using two delimiters.
The code is mostly copy-pasted from strtok manpage. I've tried to find some simpler solution using glib, but it looks like this is probably the easiest way to split string using two repeating delimiters.
Fixes #637
> Fix parsing crypttab with multiple spaces 

- src/udiskslinuxmdraid.c
> mdraid: Fix order of device names in "add disk" error message

- modules/iscsi/udisksiscsitypes.h
- modules/iscsi/udisksiscsiutil.c
- modules/iscsi/udisksiscsiutil.h
- modules/iscsi/udiskslinuxiscsisession.c
- modules/iscsi/udiskslinuxmanageriscsiinitiator.c
This ports the code for getting and setting initiator name to a proper
GKeyFile parser in order to handle comments, examples and multiple keys
in the config file properly. Some distributions do ship custom complex
config files by default.
Note that GKeyFile parser requires keys to always belong to some group,
for this we create a fake group in memory and strip it again when writing
the file back. This way we preserve all comments.
This commit also includes minor code cleanup and refactoring.
---
Fixes #650
> iscsi: Use proper parser to get and set initiator name

- data/org.freedesktop.UDisks2.xml
- doc/udisks2-sections.txt.in.in
- src/udiskslinuxfilesystem.c
- src/udisksstate.c
- src/udisksstate.h
Although the race condition itself could've been fixed by adding sleep long enough to guarantee the udisks clean functions would run, I think this may be actually useful to someone.
> Always remove mountpoint created by udisks upon unmount

- src/udisksmountmonitor.c
The mounts list is actually being accessed from different threads.
Not only read but also the fill may be triggered from outside,
however improbable that is.
----
Needed for #664
> udisksmountmonitor: Add locking around the mounts list

- modules/bcache/udiskslinuxmanagerbcache.c
- modules/lvm2/udiskslinuxlogicalvolume.c
- modules/lvm2/udiskslinuxmanagerlvm2.c
- modules/lvm2/udiskslinuxvolumegroup.c
- modules/vdo/udiskslinuxmanagervdo.c
- modules/zram/udiskslinuxmanagerzram.c
- src/udiskslinuxdevice.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxloop.c
- src/udiskslinuxmanager.c
- src/udiskslinuxmdraid.c
Couple of tiny fixes. Of course this breaks translations :-)
Spot the difference:
```
dbus.exceptions.DBusException: org.freedesktop.UDisks2.Error.Failed: Error waiting for logical volume object for udisks_test_origin_lvTimed out waiting for object
dbus.exceptions.DBusException: org.freedesktop.UDisks2.Error.Failed: Error waiting for VDO object after creating udisks_activate_test: Timed out waiting for object
```
> Error message prefixes

- src/udiskslinuxfilesystem.c
- src/udisksmountmonitor.c
- src/udisksmountmonitor.h
On Endless OS, all systems have the following /etc/fstab:
LABEL=ostree / ext4  errors=remount-ro 0 0
If you insert a removable device containing a filesystem with the label 'ostree', then asks UDisks to mount it, it will attempt to mount it over /. If the filesystem is not of type ext4, this will fail; if it is, this will succeed, with potentially disastrous results.
There is already a check in is_in_fstab() which constructs the path to the /dev/disk/by-label/$LABEL symlink and compares it to the device being mounted. However, in this scenario that comparison succeeds: the symlink is updated when the new device is detected.
To prevent this, use UDisksMountMonitor to look up the mount point specified in fstab (using a new get_mount_for_path accessor); if an existing mount is found, and it …
> Filesystem: ignore fstab entry if another device is mounted there

- src/udisksmountmonitor.c
Related to the recently merged addition. Again this function may be called
from side threads.
----
Related to #664
> udisksmountmonitor: Add locking around udisks_mount_monitor_get_mount_for_path()

- src/tests/integration-test
Not sure what has changed in the kernel or udev, however triggering udev
is not enough to detect a filesystem on a CD-ROM scsi_debug device.
Coincidentally while blkid would then detect a filesystem properly, udev
still doesn't notice it and manual trigger is needed.
This fixes failing ext4 integration tests, however the scsi_debug module
can't be unloaded after successful run for unknown reason. That's an
unrelated issue however.
> integration-test: Force re-read partition table on a sr0 scsi_debug device

- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
cryptsetup is not thread safe, we need to make sure we are not
calling 'crypt_init' multiple times from different threafs.
This fixes only calls not covered in 25be16d
> Fix cryptsetup calls locking

- packaging/udisks2.spec
Submitted-by: Milan Crha <mcrha@redhat.com>
> spec: Do not hardcode sysconfdir to /etc (#1729430)

- src/tests/dbus-tests/test_20_LVM.py
When attaching an LV as a cache pool to another LV, LVM allocates
space for the cache metadata (while converting the LV to a cache
pool).
> Leave 8 MiB for cache metadata in the LVM test

- src/tests/integration-test
exFAT can be mounted with '-o rw' even if the device is read only,
it will just mount it read only.
Fixes #680
> integration-test: Skip read only mounting test for exFAT

- doc/udisks2-sections.txt.in.in
- udisks/udisksclient.c
- udisks/udisksclient.h
Currently UDisksClient objects always talk to udisksd on the system bus.
This is fine for normal use, but unit tests may want to spin up a
private dbus-daemon using GTestDBus and have udisks use that, to isolate
the tests from the host. So this commit adds a new constructor so that a
GDBusConnection object can be passed in and used during initialization
of the UDisksClient. Also, reword a comment which seemed to imply that
UDisksClient objects are singletons (which they are not).
Before adding this feature we (in an Endless project) were setting
DBUS_SYSTEM_BUS_ADDRESS to the address of the GTestDBus daemon, to trick
udisks into using that daemon. However this led to intermittent unit
test failures when some I/O happened on the connection after the daemon
had been killed by …
> udisksclient: Let the caller specify a D-Bus connection

- tools/udisksctl.c
Previously, the PartitionTable serialization looked like this:
/org/freedesktop/UDisks2/block_devices/nvme0n1:
org.freedesktop.UDisks2.PartitionTable:
Partitions:         ['/org/freedesktop/UDisks2/block_devices/nvme0n1p2', '/org/freedesktop/UDisks2/block_devices/nvme0n1p1', '/org/freedesktop/UDisks2/block_devices/nvme0n1p3']
Type:               gpt
With this change, Partitions is formamtted like Block.Symlinks and other
array-of-string-like properties:
/org/freedesktop/UDisks2/block_devices/nvme0n1:
org.freedesktop.UDisks2.PartitionTable:
Partitions:         /org/freedesktop/UDisks2/block_devices/nvme0n1p2
/org/freedesktop/UDisks2/block_devices/nvme0n1p1
/org/freedesktop/UDisks2/block_devices/nvme0n1p3
Type:               gpt
> udisksctl: pretty-print 'ao' properties

- src/tests/dbus-tests/test_40_drive.py
Behaviour change in the default `__str__` method for object in
Python 3.8 caused that converting dbus.UInt variables no longer
works as expected. We need to convert these values to int first.
Python 3.8:
>>> str(dbus.Int64(1))
'dbus.Int64(1)'
Python 3.7 (and older):
>>> str(dbus.UInt64(1))
'1'
> Fix converting dbus.UInt values to string with Python 3.8

- src/tests/dbus-tests/udiskstestcase.py
Default converter tries to convert the message using decode() and
if it fails it will return bytes (which then fail to convert in
our code). This change adds custom converter for the MESSAGE key
that replaces the non-unicode characters.
> dbus-tests: Fix decoding journal messages with non-unicode data

- src/tests/dbus-tests/test_70_encrypted.py
This is new version of #689. There are no changes needed in UDisks because the original behaviour was bug in cryptsetup (the integrity device "under" LUKS should be marked as private) so this only adds the test to check if we can correctly open a LUKS device with integrity.
> Add test for unlocking LUKS2 devices with integrity

- packaging/udisks2.spec
VDO is not available there and we don't build libblockdev VDO
plugin either.
> Do not try to build VDO module on RHEL 7 on non-x86_64 arches

- tools/udisksctl.c
When I use `udisksctl mount -b /dev/sda1` at this moment the output is:
`Mounted /dev/sda7 at /run/media/meeuw/2f9b224e-a729-4ae5-9ef6-02aaeb7a7fa6.`
If I double click the path in gnome-terminal to select and copy/paste the output to ie. `cd ` the path is selected including the dot (`.`) which is highly annoying because that path doesn't exist.
Could the dot please be removed from the output? I would also settle for a trailing slash or an additional space before the dot.
> remove dot (.) for easier selecting the mounted folder

- packaging/udisks2.spec
Backport from Fedora:
https://src.fedoraproject.org/rpms/udisks2/pull-request/3
> rpm: Don't trigger udev if socket is not accessible

- src/udiskslinuxdriveata.c
Certain SATA drives seem to only honour the standby timer value if
the APM level has been set previously.
Just a simple block of code reorder (the diff might indicate something else).
Closes: #694
> ata: Reorder setting of APM and Standby timer flags

- src/tests/dbus-tests/test_80_filesystem.py
This was discovered thanks to recently added support for F2FS to
libblockdev -- UDisks automatically detects we can now resize it
but it can't check it's current size which causes the test to fail.
> tests: Skip resize tests for formats without function to get size

- src/udisksspawnedjob.c
We want to be able to read binary data from the stderr and stdout of
spawned processes, so unset the encoding for those channels — otherwise
it will be validated as UTF-8 and invalid data (particularly embedded
nuls) will be dropped.
GLib became stricter at validating this with
https://gitlab.gnome.org/GNOME/glib/merge_requests/967 in GLib 2.63.0,
but it’s not an API break.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
Fixes: #724
> udisksspawnedjob: Clear encoding of stdout and stderr channels

- src/tests/dbus-tests/test_60_partitioning.py
We can't assume that the free space in the extended partition will
start at a fixed position, we should use end of the previous
logical partition instead.
This is related to the ongoing rewrite of libblockdev to libfdisk (see https://github.com/storaged-project/libblockdev/pull/455). Optimal partition alignment is slightly different in libfdisk, especially for logical partitions where libfdisk leaves more free space between these (up to 1 MiB) so we should use end of the previous logical partition + 1 as the offset and let fdisk align it. This is also what GNOME Disks uses when creating a new (logical) partition.
> Use relative logical partition start in partitioning tests

- data/org.freedesktop.UDisks2.xml
- doc/man/udisksctl.xml.in
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxencrypted.c
- tools/udisksctl.c
I've noticed this TODO when working on the BitLocker support, so one less TODO for us :-)
> Allow unlocking encrypted devices as read only

- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxblock.c
- src/udiskslinuxdrive.c
- src/udiskslinuxpartition.c
The `_ENC` udev properties contain escaped "unsafe" characters and
we try to un-escape these and convert to UTF-8 where possible.
Instead of cutting the non UTF-8 part of the string we should
fallback to the safe udev strings (with all unsafe characters
replaced with "_") where possible.
Fixes: #718
> Fallback to safe udev values where possible for non UTF-8 strings

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/skip.yml
- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_90_swapspace.py
- src/tests/dbus-tests/test_btrfs.py
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/test_vdo.py
- src/tests/dbus-tests/test_zram.py
- src/tests/dbus-tests/udiskstestcase.py
Few changes for running tests (DBus tests only in this case) inspired by libblockdev test suite. The biggest change are the test tags. I've not tagged the tests yet (other than converting existing "unsafe" and "unstable" decorators to the new tags), because I'm not sure if we want to use all tags that libblockdev uses -- do we want to mark also "slow" tests (to be able to run just quick tests, instead of the entire suite which takes around 1 hour) and select a subset of "core" tests for even quicker sanity checks?
Note I will adjust the jenkins PR job to run "stable" and "unstable" tests separately before merging this.
> dbus_tests: Test tags and other run_tests.py improvements from libblockdev

- src/tests/dbus-tests/test_70_encrypted.py
These versions doesn't support BitLocker superblock detection.
This should fix failing tests on CentOS 8 Stream. After a recent update of cryptsetup it's the only system with a new cryptsetup which supports BitLocker and old util-linux/blkid which does not.
> Skip BITLK tests on systems with util-linux older than 2.33

- src/udisksbasejob.c
- src/udisksprovider.c
This has been deprecated since glib-2.58
> daemon: Port away from G_TYPE_INSTANCE_GET_PRIVATE()

- src/tests/dbus-tests/test_mdraid.py
This should fix some of the failing unstable mdraid DBus tests.
> dbus-tests: Fix expected MD_DEVICE key in mdadm --detail output

- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_vdo.py
- src/tests/dbus-tests/udiskstestcase.py
We already have a similar code in libblockdev. Especially on rawhide the module is often present but can't be loaded so just checking for its presence is not enough for skipping.
> dbus-tests: Skip VDO and LVM VDO tests if we can't load the module

- src/tests/dbus-tests/test_70_encrypted.py
The typo in the error message has been fixed in libblockdev
recently.
> dbus-tests: Fix expected error message for failed LUKS resize

- modules/bcache/udiskslinuxblockbcache.c
- modules/btrfs/udiskslinuxfilesystembtrfs.c
- modules/iscsi/udiskslinuxiscsisessionobject.c
- modules/lsm/lsm_linux_drive.c
- modules/lvm2/udiskslinuxlogicalvolume.c
- modules/lvm2/udiskslinuxphysicalvolume.c
- modules/lvm2/udiskslinuxvdovolume.c
- modules/lvm2/udiskslinuxvolumegroup.c
- modules/lvm2/udiskslinuxvolumegroupobject.c
- modules/vdo/udiskslinuxblockvdo.c
- modules/zram/udiskslinuxblockzram.c
- src/tests/integration-test
- src/udiskslinuxblock.c
- src/udiskslinuxdrive.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxfilesystem.c
- src/udiskslinuxloop.c
- src/udiskslinuxmdraid.c
- src/udiskslinuxpartition.c
- src/udiskslinuxpartitiontable.c
- src/udiskslinuxswapspace.c
Found a minor race condition in the `GDBus` code where clients didn't get property change notification (in time) that led to random test failures. Hopefully this will make things more stable, although I didn't really try to find the root cause.
Fixes #777
> Integration test fixes

- src/tests/integration-test
It's fixing #784 , another way would be to specially case the label for exfat rather than rename the string
> integration-test: fix the exfat tests with the new util-linux

- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskscrypttabmonitor.c
- src/udiskslinuxblock.c
There was a regression in the 2.9.0 release caused by commit 9be5c4a6a4c206c726b5f08c8c9d9fd132805ae4.
This also reworks crypttab monitor caching.
Closes #751
> Teardown fixes

- AUTHORS
Vratislav left Red Hat few years ago and no longer maintains
UDisks.
> AUTHORS: Add tbzatek as the maintainer

- src/tests/dbus-tests/test_10_basic.py
Resize support for nilfs2 was recently added to libblockdev so
UDisks now also support it.
> tests: Do not use nilfs2 as an example of non-resizable FS

- modules/lvm2/udiskslinuxvolumegroupobject.c
Just a tiny memleak found, otherwise the Valgrind log was surprisingly clean!
> lvm2: Fix leaking BDLVMVDOPooldata

- .gitignore
- Makefile.am
- configure.ac
- src/tests/Makefile.am
- src/tests/dbus-tests/Makefile.am
- src/tests/dbus-tests/test_10_basic.py
Runtime detection against running distribution and available executables
was always a problem to keep in sync. Use actual list of build-time
enabled modules instead.
> tests: Test modules that are actually enabled during build

- data/builtin_mount_options.conf
New in kernel 5.10, a handy security hardening feature.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dab741e0e02bd3c4f5e2e97be74b39df2523fc6e
> mount options: Allow 'nosymfollow' mount option for unprivileged mounts

- src/udiskslinuxblock.c
The rest of UDisks2 takes care to do the right thing when
/etc/crypttab is missing, and treats that case as a empty file.  Thus,
add_remove_crypttab_entry should do the same.
> udiskslinuxblock: Survive a missing /etc/crypttab

- src/udisksstate.c
Too confusing for users, actually gets logged among the daemon messages.
Most D-Bus method handlers locking the block device queue an explicit
cleanup once finished so this message is effectively useless anyway.
> udisksstate: Silence the block device busy messages on cleanup lock

- doc/udisks2-sections.txt.daemon.sections.in
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxblockobject.c
- src/udiskslinuxmanager.c
This will trigger extra uevent after loop device setup to ensure all objects are updated.
Resolves #800 
Resolves #817
Resolves #580
Resolves #828
> Fix loop device setup

- src/tests/dbus-tests/test_40_drive.py
This is prone to failures due to occasional changes on the kernel
side. Besides some device identifiers may be affected by sg3_utils
scsi udev rules.
> tests: Remove scsi_debug serial number checks

- src/tests/dbus-tests/test_zram.py
Some distributions now employ zram in their default installations
and it conflicts with the UDisks way of zram management.
> tests: Skip zram tests if zram module is already loaded

- packaging/udisks2.spec
This disables building of the standalone VDO udisks2 module and
removes the udisks2-vdo subpackage. The preferred LVM-VDO way
remains untouched by this change.
----
This is a first step to remove standalone VDO support towards the 2.10.0 goal.
> spec: Remove VDO support

- src/tests/dbus-tests/test_10_basic.py
The resize functionallity is no longer provided by libblockdev
fs module directly, "vfat-resize" tool is now required so we need
to check for its availability in the test.
> tests: Fix checking if VFAT is resizable

- src/udiskslinuxblockobject.c
None of the conditions are supposed to ever fail until really bad things happen.
> udiskslinuxblockobject: Add safety checks for UDisksLinuxBlock interface

- src/udiskslinuxpartition.c
We need to force UDev to update the value in the database. We
already do this in other similar partition functions when chaning
name or flags.
> udiskslinuxpartition: Trigger uevent after changing partition type

- src/udiskslinuxblock.c
- src/udiskslinuxfsinfo.c
This is a quick and ugly workaround reverting back the old behaviour until we sort out all the related issues and find a proper way across the storage stack (#859)
The rule of thumb here is that UDisks is just a tool and its consumers with higher level logic should be aware of what they're doing.
References:
https://github.com/dosfstools/dosfstools/releases/tag/v4.2
https://github.com/storaged-project/libblockdev/pull/618
Closes #851
> dosfstools >= 4.2 quirks

- data/org.freedesktop.UDisks2.policy.in
Fix two comments: A copy & paste error in line 109, and a typo / spelling error in line 403
> Fix two comments (one copy'o, one typo)

- src/tests/dbus-tests/test_drive_ata.py
Some of the tests operate on physical ATA drives, comparing values between
smartctl output and udisks. Different libraries used, different approach
to retrieve some ATA features and values. Turned out this is not working
correctly on some SATA disks with each approach giving slightly different
results, presumably for the quirks in place.
> tests: Mark Drive.ATA tests as unstable

- udisks/udisksclient.c
While any given Block object has at most one corresponding Drive, many
Block objects may share the same Drive. One example is eMMC devices
which provide a block device for the main data area (e.g. /dev/mmcblk0)
as well as additional logical block devices for device partitions (e.g.
/dev/mmcblk0boot0 and /dev/mmcblk0boot1).
This behaviour was introduced in #834 to resolve issue #619 that these
device partitions caused a phantom additional Drive object to be
exposed. On that issue, I wrote:
> I believe that Block.Drive on the boot partitions should point to the
> same data area as the main data area (and its logical partitions);
> udisks_client_get_block_for_drive() on the drive should return
> /org/freedesktop/UDisks2/block_devices/mmcblk0.
The first part is now true, but as described on …
> udisksclient: Make get_block_for_drive deterministic

- src/udiskslinuxfsinfo.c
The currently used mkexfatfs is only available in exfat-utils and not in
the new exfatprogs. Unfortunately those project use different arguments
to set the label so workaround by not setting it...
https://github.com/storaged-project/udisks/issues/882
> Use the mkfs command to format exfat partitions

- doc/udisks2-sections.txt.daemon.sections.in
- src/tests/dbus-tests/test_10_basic.py
- src/udisksconfigmanager.c
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxmanager.c
Although the current way of mocking up a module soname filepath leaves very little room for exploitation, it's generally wise to constrain allowed characters in a module name.
> Module naming limitation

- src/udiskslinuxdriveata.c
Should fix a leaking GThread without a need to join or track it anyhow.
> udiskslinuxdriveata: Use GTask to apply configuration in a thread

- src/udiskslinuxprovider.c
Sometimes a stray 'change' uevent with a wrong sysfs path is sent for a device
that demands attention or to indicate that media has changed. Such uevents
often carry no useful information and while the major:minor numbers match
a physical device, the sysfs path often don't match. That creates a trouble
to the current sysfs-to-block mapping and a new phantom object is being created.
As these uevents are rather rare the object may stay exported on the D-Bus
object manager forever as no 'remove' uevent is ever received. That in turn
creates object naming conflict when a device with the same major:minor numbers
and different sysfs path appears.
The attributes in question are DISK_MEDIA_CHANGE=1 and DISK_EJECT_REQUEST=1.
See the kernel block/genhd.c sources for further reference.
Let's just …
> udiskslinuxprovider: Filter out spurious uevents

- packaging/udisks2.spec
- udisks/udisks2.conf.in
LUKS2 is mature enough so we should make it default everywhere
not only on RHEL.
> Set default LUKS version to LUKS2

- src/tests/dbus-tests/test_30_iscsi.py
- src/tests/dbus-tests/udiskstestcase.py
There's an issue somewhere within the `open-iscsi` library handling the actual initiator login, sometimes causing timeouts after roughly 120 seconds. That however exceeds the default tests D-Bus method call timeout of 100 seconds, leading to test failures. Also since the `libiscsi` (or the UDisks iscsi module) has a global lock and the daemon is still handling that previous method call, all further tests would lock and wait, causing further test failures (timeouts).
> iSCSI timeouts

- src/udiskslinuxmanager.c
Minor fix for failing mdraid tests where UDisksLinuxMDRaidObject
didn't get created due to a missed uevent.
> udiskslinuxmanager: Trigger uevent on a newly created mdraid array

- src/tests/dbus-tests/run_tests.py
When running tests with --include-tags=all we should not skip
non-existing tests and tests that fail to load and let unittest
show the exception instead.
> dbus_tests: Fix including non-existing tests based on tags

- data/builtin_mount_options.conf
> Add (no)autodefrag to list of allowed btrfs mount options

- src/udiskslinuxblock.c
Trigerred by libblockdev part tests.
> udiskslinuxblock: Handle missing parent device while looking up drive for block

- src/tests/dbus-tests/force_clean.py
- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_19_lsm.py
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_btrfs.py
- src/tests/dbus-tests/test_zram.py
- src/tests/integration-test
Basically same change as https://github.com/storaged-project/libblockdev/pull/657, we are using some helper functions from `distutils` in tests.
> Distutils deprecation

- src/udisksmountmonitor.c
Under very unlikely circumstances the block device number of a mount can match block device number of a swap (that is itself resolved via `/dev` symlinks) and a assertion warning is printed on the console about unexpected `UDisksMount` type. Functional-wise there would be no difference as `NULL` compares to `NULL`. Since the `UDisksMountMonitor` reads and parses `/proc/self/mountinfo` and `/proc/swaps` sequentially there's naturally a slight chance for a race condition leading to such conflict. The additional file checksum tests within `udisks_mount_monitor_ensure()` should however decrease a chance of this happening.
Changes in this pull request bring additional safety checks though no functional change should be observed.
> Mount monitor improvements

- configure.ac
- modules/lvm2/jobhelpers.h
- modules/lvm2/udiskslinuxmanagerlvm2.c
- src/tests/test.c
- src/udisksdaemonutil.c
- src/udiskslinuxblockobject.c
- src/udiskslinuxencryptedhelpers.h
- src/udiskslinuxfilesystemhelpers.h
- src/udiskslinuxmanager.c
- src/udiskslinuxmdraidhelpers.h
It was certainly interesting to see major differences in code analysis and how different the actual generated code was. Undefined corner cases or silent stack corruption went unnoticed for years with gcc while the same code failed immediatelly in the clang case.
Fixes #891
Closes #853
Closes #852
Closes #806
> clang fixes

- src/tests/dbus-tests/test_10_basic.py
We can't really check for libblockdev version in the tests and
there is a difference between 2.x (compiled in) and 3.x (tool)
support for VFAT resize so the test_40_can_resize test case needs
to be adjusted to work with both.
> Fix checking for VFAT resize support with older libblockdev

- src/tests/dbus-tests/Makefile.am
With no modules enabled the UDISKS_MODULES_ENABLED variable is set
to "{ }" which is interpreted as empty dict by Python and not an
empty set as expected by the test suite.
> Fix tests config with no modules enabled

- src/tests/dbus-tests/test_20_LVM.py
This adds a check for the created stack objects presence after the teardown.
Due to the nature of the global lvm2 module update some objects may still
hang around after the org.freedesktop.UDisks2.VolumeGroup.Delete(options='tear-down')
method call has returned. Until this is properly fixed an explicit timeout
had to be added.
See also #814
> tests: Add LVM2 teardown object existence checks

- src/udiskslinuxdriveata.c
When checking IO stats after get_pm_state the noio bool will never become true
because get_pm_state() reads from the disk. If we perform the check earlier and
there was no IO on the disk, noio will become true and smart update refresh will be canceled.
This fixes the problem with StandbyTimeout not working if the timeout is bigger then 10 minutes.
> udiskslinuxdriveata:Fix reading IO stats on ata_refresh_smart_sync

- tools/udisksctl.c
Segfault when trying to power-off a dbus object which does not implement
the "org.freedesktop.UDisks2.Drive" interface.
> udisksctl: fix segfault

- tools/udisksctl.c
In order to autocomplete the "power-off" command we need to:
1. Search for all dbus objects associated to the "org.freedesktop.UDisks2"
service and...
2. ...only keep (and show as autocompletion possibilities) the ones
than meet "certain criteria".
That "certain criteria" is what this patch changes.
BEFORE this patch the filtering criteria was:
- Objects that implement the "org.freedesktop.UDisks2.Drive.Ata" interface.
AFTER this patch the new criteria is:
- Objects that implement the "org.freedesktop.UDisks2.Drive" interface and...
- ...its "CanPowerOff()" method returns true.
Was the old criteria a bug? I don't know... but my USB dongles now
appear in the autocomplete list and didn't before this patch.
> udisksctl: fix autocomplete for power-off command

- tools/udisksctl.c
The bash completions seem to miss a number of the options. It looks like priority was those options that take arguments but it is useful to list all. I could have added them individually but it seems cleaner to make use of the existing list that is there for glib's option parsing. The change here adds a `list_options()` functions which iterates over the existing `GOptionEntry` array to list the long options. So all options are now listed (except `--help`) and any new future ones will get picked up automatically.
Where the existing code does, e.g `opt_unlock_lock_object_path == NULL` that check could also be factored into the new function. This allows for some cleanup of the code. The logic could be further cleaned up where checking the `completion_objects` etc variables because …
> when printing options for completion iterate over existing structures

- data/Makefile.am
- data/completions/_udisks2
- packaging/udisks2.spec
This change adds a completion function for zsh similar to the existing one for bash. This makes use of the hidden udisksctl complete command to generate matches but, unlike for bash, leaves matching of completion candidates to zsh.
I've also included the necessary build file changes to install this in the canonical location – `$PREFIX/share/zsh/site-functions`
Note that naming the function _udisks2 (rather than, e.g. _udisksctl) is also in line with zsh naming conventions.
> add a completion function for zsh

- tools/udisksctl.c
Just a couple of precautionary checks that the retrieved objects are valid.
> udisksctl: Add extra guards around retrieved objects

- src/tests/dbus-tests/test_20_LVM.py
Apparently the bios_in_write value is now 0 for newly created VDO
pools and because we use it for the writeAmplificationRatio
calculation we get zero too.
------
We probably should create a filesystem on the VDO LV and write something to it, to get some valid statistics to check, but TBH I don't want to fix this for every release so I think just not doing a sanity check on the value and hoping that VDO works is the best we can do.
> tests: Do not check that writeAmplificationRatio is bigger than 0

- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
> lvm2: Document empty pool_name allowance for CreateVDOVolume()

- doc/udisks2-sections.txt.daemon.sections.in
- modules/btrfs/udiskslinuxfilesystembtrfs.c
- src/udisksstate.c
- src/udisksstate.h
Separated from #838 that is likely going to be WIP for a very long time to get at least some minor fixes in.
> Misc. btrfs fixes

- src/udiskslinuxswapspace.c
No idea why but I've recently noticed failing `test_90_swapspace.UdisksSwapSpaceTest.test_20_start_stop` tests. Looking at the code this was one of the few remaining places where an explicit uevent was not trigerred.
> udiskslinuxswapspace: Trigger uevent on swap start/stop

- src/udiskslinuxprovider.c
Updating all existing block objects on any utab change
was unnecessary and overly expensive. With the UDisksUtabMonitor
providing specific utab entry, update just block objects
with matching device file.
Note that there is a room for similar optimization in fstab
and crypttab monitoring.
Fixes #869
> udiskslinuxprovider: Only update related objects on utab changes

- doc/udisks2-sections.txt.daemon.sections.in
- src/udisksata.c
- src/udisksata.h
- src/udiskslinuxdriveata.c
- src/udiskslinuxdriveata.h
- src/udiskslinuxfilesystem.c
Filesystem size value retrieval is very expensive as it typically calls
filesystem tools that read superblock -> doing some I/O. Other
filesystem properties are typically retrieved from existing stateful
sources, either udev or sysfs.
This change overrides the gdbus-codegen-generated GDBusInterfaceSkeleton
property retrieval and adds a custom hook that retrieves the filesystem
size value when actually requested.
One limitation of such approach is that the hook is called with
the GDBusObjectManager lock held and thus the hook needs to be as minimal
as possible and needs to avoid any access to any GDBusObject.
TODO: handle ATA power management.
Fixes #946
Fixes #911
Fixes #871
Fixes #868
> udiskslinuxfilesystem: Make 'size' property retrieval on demand

- src/udiskslinuxdriveata.c
If refresh_smart_sync is aborted because nowakeup and noio we
need to update io_stats again. If not not bool noio will become
false on the next run because get_pm_state reads frome disk.
> udiskslinuxdriveata:Fix updating IO stats on ata_refresh_smart_sync

- modules/bcache/Makefile.am
- modules/btrfs/Makefile.am
- modules/lvm2/Makefile.am
When building udisks with `--enable-btrfs` using slibtool instead of GNU libtool the build will fail with undefined references.
This is because of a missing dependency for `libudisks2_btrfs.so` and GNU libtool will hide this issue by silently ignoring `-no-undefined` while slibtool does not.
Note that this is reproducible with GNU libtool if the `-no-undefined` for `libudisks2_btrfs_la_LDFLAGS` is changed to `-Wl,-no-undefined` where it is then explicitly passed to the linker.
Gentoo Bug: https://bugs.gentoo.org/782061
Full build log: [udisks.slibtool.log](https://github.com/storaged-project/udisks/files/8663463/udisks.slibtool.log)
> modules/btrfs: Add missing dependency

- data/builtin_mount_options.conf
- data/org.freedesktop.UDisks2.xml
- doc/configurable_mount_options.xml
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
- src/udiskslinuxmountoptions.c
- src/udiskslinuxmountoptions.h
- udisks/mount_options.conf.in
This enhances the configurable mount options with filesystem drivers definitions and priorities that are then reflected in actual mount process with multiple attempts to mount until a filesytem driver is known to the kernel.
TODO:
Fixes #945
Fixes #932
> Differentiate filesystem signatures and filesystem drivers

- src/udiskslinuxfilesystem.c
Libblockdev 3.0 will change API for some of the "generic"
filesystem functions to allow passing filesystem type to them
instead of forcing libblockdev to probe the device. Because UDisks
knows the filesystem type, we can provide it to libblockdev.
https://github.com/storaged-project/libblockdev/pull/758 needs to merged first.
> Adjust to new libblockdev API for generic FS functions

- src/tests/dbus-tests/test_loop.py
There's a bug in the kernel 5.18.4+ versions introduced by
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.18.4&id=4c10e26c35634bf9e9b625e4dd48d21d26c7ed1d
The unset LO_FLAGS_PARTSCAN flag is not honoured and partitions
are scanned either way.
> tests: Mark loop partscan tests as unstable

- src/udisksstate.c
Just a debugging measure in case the realpath(3) call fails.
> udisksstate: Provide more context on realpath() errors

- src/udiskslinuxnvmenamespace.c
Interestingly this is needed only on CentOS/RHEL 8, I guess on other systems errno.h is brought in with some of the other includes.
> udiskslinuxnvmenamespace: Include errno.h to fix compilation on CentOS 8

- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
XFS now requires at least 300 MiB of space, let's pick something
lighther.
> tests: Use ext4 instead of xfs in non-filesystem tests

- src/udiskslinuxblock.c
- src/udiskslinuxdriveata.c
> Restrict Block.Format() ATA secure erase on top-level block objects only

- .github/workflows/rpmbuild.yml
I need to figure out either how to automate this or move the definition of Fedora versions to one place. Updating three repositories every 6 months isn't that bad, but still could be easier.
> ci: Update Fedora versions for RPM build tests

- src/tests/integration-test
Not sure whether this should use the configured prefix or not. Haven't even found where this message comes from:
```
make integration-tests
make[1]: Entering directory '/home/jenkins/workspace/udisks-pr/arch/x86_64/distro/centos_8s/type/udisks'
make all &>/dev/null
cd src/tests && sudo python3 ./integration-test | tee -a ../../integration_tests_output.log \
&& echo "integration-tests: SUCCESS" >> ../../RESULTS || echo "integration-tests: FAILED" >> ../../RESULTS
The directory /usr/local/var/run/udisks2 does not exist; please create it before running these tests.
Testing binaries from local build tree
```
> tests: Create required directories for integration tests

- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/integration-test
Some of the errors and messages changed with the rewrite to the libblockdev 3.0 API.
> Fix some expected error messages in FS integration tests

- src/udiskslinuxblock.c
This function will be removed in libblockdev 3.0, we can get
UUID from the bd_crypt_luks_info.
https://github.com/storaged-project/libblockdev/pull/614 needs to be merged first (`bd_crypto_luks_info` currently returns error when called with the backing block device)
> Do not use bd_crypto_luks_uuid to get UUID of LUKS devices

- src/tests/dbus-tests/test_nvme.py
- src/udiskslinuxnvmecontroller.c
- src/udiskslinuxnvmenamespace.c
Due to the way how the kernel host nvme driver reports command failures we need to limit the number of commands sent to the device. The most safe way of trying and failing, even with some kind of "not supported" error that can be safely ignored, doesn't unfortunately work as kernel would report the error anyway. The only way to prevent this is to check the controller and namespace feature flags that however don't fully align with the actual calls. But it's the best guess we have.
Broken NVMe standard implementation on the device side will result in bogus errors reported, so let's see what will users report...
> nvme: Feature flags

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
Issues found by the CI, though not obvious on the first sight, reproduced only by a slightly different test set. Just another example of issues that are hidden in certain sequential test execution order, would be nice to randomize the tests.
> Mount options fixes

- modules/iscsi/udisksiscsiutil.c
- src/tests/dbus-tests/test_30_iscsi.py
In case of reusing a context auth info needs to be always set to override previous data.
> iscsi: Always set auth info

- modules/iscsi/data/org.freedesktop.UDisks2.iscsi.xml
- src/tests/dbus-tests/test_30_iscsi.py
The test LIO target config expects a specific initiator name as set by the ACLs. However the iscsid daemon only seems to be reading the InitiatorName string on startup and in case the service is running with a different name, the auth tests will fail.
As a workaround, restart the iscsid service after each change. A proper way through libiscsi or libopeniscsiusr would be nice -> TODO.
> tests: Restart iscsid on every InitiatorName change

- src/tests/dbus-tests/test_10_basic.py
This is a partial revert of commit cf47eeeae1 that depends on full object update after partitioning. That is still work in progress (see #955) and prone to race conditions.
======================================================================
FAIL: test_60_resolve_device (test_10_basic.UdisksBaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/jenkins/workspace/udisks-pr/arch/x86_64/distro/centos_9s/type/udisks/src/tests/dbus-tests/test_10_basic.py", line 335, in test_60_resolve_device
self.assertEquals(part_name_val, part_label)
AssertionError: dbus.String('', variant_level=1) != 'PRTLBLX'
> tests: Remove resolve_device tests involving partition creation

- src/udiskslinuxfilesystem.c
The fallbacks for the lack of POSIX Access Control Lists support in the kernel [1] and the absence of libacl as a build-time dependency [2] were different.  The former fell back to changing the ownership of the directory to the user's UID and latter changed it to the GID.
Changing the ownership of /run/media/$USER to the user's GID is slightly better [3] because it allows the user to still navigate inside the directory but prevents them from creating arbitrary files in it or changing the permissions.  However, it's still not as good as ACLs because other users belonging to the same GID will also have the same level of access.
To achieve the above, /run/media/$USER is always created as 0750, even when libacl is present as a build-time dependency.  Otherwise, changing it's ownership to the …
> udiskslinuxfilesystem: Tighten the fallback for kernels without ACL

- data/80-udisks2.rules
Just like "ram*" block devices, they are better not shown to the user since they don't behave as expected of block devices.
> udev: Also ignore "zram*" block devices

- src/tests/dbus-tests/test_70_encrypted.py
bd_crypto_luks_uuid is deprecated and will be removed in 3.0
> tests: Use bd_crypto_luks_info instead of bd_crypto_luks_uuid

- configure.ac
For some reason a colon (:) character is used in a msgfmt command detection failure case, causing troubles further in the build. Add an explicit check for empty string and the colon char.
Fixes #915
> build: Add explicit check for msgfmt

- src/tests/dbus-tests/test_btrfs.py
The error message now says "unknown data profile".
> tests: Fix expected error when creating an invalid btrfs RAID

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
Here's a first attempt at fixing this problem. Apart from non-printable characters I also decided to remove a few other dangerous ones.
Ascii and non-ascii characters are treated separately as an optimization, but it's also possible to get rid of the ascii path altogether.
Fixes #1056
> udiskslinuxfilesystem: Sanitize label when creating the mount point

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxblock.c
This allows the user to pass an arbitrary set of command-line options to the mkfs tool.
Although mkfs options are generally stable and backward compatible, UDisks itself provides no guarantees and it's the responsibility of the user to make sure that the provided options actually work with the versions of the software available in the system.
Fixes #583
> Add 'mkfs-args' to Block.Format()

- README.md
- configure.ac
- modules/lvm2/udiskslinuxlogicalvolume.c
- packaging/udisks2.spec
We don't need any special dependency for LVM cache so it doesn't make sense to make the support optional.
> Remove the separate configure option for LVM cache support

- src/tests/dbus-tests/test_80_filesystem.py
This works fine since it was fixed in libblockdev:
https://github.com/storaged-project/libblockdev/commit/e97c6cb40fb31a6bc0d3470c32b661885db2187e 
https://github.com/storaged-project/libblockdev/commit/a56c88c8e05377bbc5277aa7836da5cf09f3f9a8
> tests: Fix test_mountpoint_utf8 with EXFAT

- data/org.freedesktop.UDisks2.policy.in
- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_80_filesystem.py
- src/udisksdaemonutil.c
- src/udisksdaemonutil.h
- src/udiskslinuxfilesystem.c
Here's my first attempt to implement this. Note that this a draft so the documentation and tests are still missing. First I would like to know if you are happy with this approach or if you prefer a different one.
In short:
* `Filesystem.Mount()` gets a new parameter: `as-user` (I'm open to other names). This is a user name, not a uid.
* If it is set and the user exists then a new action is used: `filesystem-mount-other-user`. This has `auth_admin_keep` for the active user. 
* This new action is used also for all drives (system and non-system ones). Do we need `filesystem-mount-system-other-user`?
I also thought about not adding any new action and instead of that requesting authentication with the existing actions when the `as-user` parameter is set. However I think that this would require …
> Extend Filesystem.Mount() to allow mounting on behalf of another user

- packaging/udisks2.spec
This package contains the liblvm2cmd library which is not used by udisks.
> packaging: Remove lvm2-devel from build dependencies

- modules/lvm2/data/org.freedesktop.UDisks2.lvm2.xml
- modules/lvm2/jobhelpers.c
- modules/lvm2/jobhelpers.h
- modules/lvm2/udiskslinuxvolumegroup.c
- src/tests/dbus-tests/test_20_LVM.py
This is a simple to understand and universal behavior that also avoids asking lvcreate to handle situations that might be too difficult for its allocation algorithm.
Alternative to #1082
> lvm2: Make as many subvolumes as PVs are given during creation

- data/org.freedesktop.UDisks2.xml
- src/udiskslinuxfilesystem.c
With the previous hack to make the Size property value retrieval on-demand no property change notification was sent since no value was actually retrieved. Chicken-egg problem, clients had no chance of knowing that something has changed.
So let's put another hack on top of the previous hack and just send out a property invalidation signal on every uevent in hope that clients would react and retrieve the value if interested in it.
This may slightly defeat the original purpose of the hack since some D-Bus bindings may proactively retrieve the invalidated value to have it cached, see e.g. the GDBusObjectManagerClient::interface-proxy-properties-changed signal. However, the benefit of deferred retrieval on daemon startup and on objects that nobody is listening to the changes on still stand. …
> udiskslinuxfilesystem: Send explicit Size property invalidation on uevent

- modules/lvm2/udiskslinuxlogicalvolume.c
- modules/lvm2/udiskslinuxmanagerlvm2.c
- modules/lvm2/udiskslinuxvdovolume.c
- src/tests/dbus-tests/test_20_LVM.py
A consequence of commit b24141f17d44238d5489ecb1336d71658ecd054f
==850== Process terminating with default action of signal 11 (SIGSEGV): dumping core ==850==  Access not within mapped region at address 0x5
==850==    at 0x4847C46: strlen (vg_replace_strmem.c:501)
==850==    by 0x4DF99DC: g_strdup (gstrfuncs.c:362)
==850==    by 0x48B1C56: UnknownInlinedFun (gstrfuncs.h:321)
==850==    by 0x48B1C56: bd_extra_arg_new (extra_arg.c:86)
==850==    by 0x9BCE55A: lvresize_job_func (jobhelpers.c:159)
==850==    by 0x14EEB5: run_task_job (udisksthreadedjob.c:214)
==850== Use of uninitialised value of size 8
==850==    at 0x9BCE563: lvresize_job_func (jobhelpers.c:158)
==850==    by 0x14EEB5: run_task_job (udisksthreadedjob.c:214)
==850==  Uninitialised value was created by a stack allocation …
> lvm2: Properly initialize stack-allocated structs

- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxpartitiontable.c
Happens frequently with protective MBR tables (vfat) that the ID_PART_TABLE_TYPE udev attribute is not set. In such cases partprobe often reports:
$ partprobe -s /dev/sdb
/dev/sdb: loop partitions 1
Thus use libblockdev libfdisk probe to see what's actually on the device.
> udiskslinuxpartitiontable: Reprobe the device in case of missing udev attributes

- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/integration-test
There's something fishy in newer kernels and read-only detection doesn't seem to work properly. As suggested in
https://github.com/util-linux/util-linux/issues/18#issuecomment-8453739 setting device ro by `blockdev --setro` seems to fix the issue.
> tests: Forcefully set scsi_debug cd drive as read-only

- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
> udiskslinuxblock: Read Bitlk UUID from the device if not provided by udev

- src/udiskslinuxfilesystem.c
... and stick to the ID_FS_LASTBLOCK * ID_FS_BLOCKSIZE calculation. Although ID_FS_SIZE equals to the above formula for some filesystem types, its designation is slightly different.
> udiskslinuxfilesystem: Do not use ID_FS_SIZE

- data/org.freedesktop.UDisks2.xml
- src/udiskslinuxfilesystem.c
- src/udiskslinuxmanager.c
One more API change in the upcoming libblockdev 3.0.
> Use BDFSResizeFlags instead of BDFsResizeFlags

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_mdraid.py
- src/udiskslinuxmanager.c
Enhanced version of #1124, reflecting API changes in https://github.com/storaged-project/libblockdev/pull/901
I've removed the validation, even though a filename value is undocumented and unsupported, it can still be passed down to `bd_md_create()` and `mdadm` and it will likely work fine.
The default when no option specified is still 'auto' as before.
Fixes #1124
> mdraid: Add 'bitmap' option to MDRaidCreate method

- data/org.freedesktop.UDisks2.xml
There are explicit checks for a mounted filesystem returning error in such a case.
> docs: Clarify mounted filesystem check/repair scenarios

- tools/udisksctl.c
Added extra checks for object validity when looking up physical device through a drive. Reproducible e.g. by calling 'power-off' over a LUKS container.
Fixes #1120
> udisksctl: Guard object lookup

- .packit.yaml
- data/Makefile.am
- modules/btrfs/data/Makefile.am
- modules/iscsi/data/Makefile.am
- modules/lsm/data/Makefile.am
- modules/lvm2/data/Makefile.am
Configure with minimal options, so that we can build a dist tarball without too many extra dependencies. In particular, we want to avoid libblockdev, as we usually need the latest upstream master one, not the distro package.
---
This is a fixed replacement of PR #1080. I got a [successful build](https://copr.fedorainfracloud.org/coprs/packit/martinpitt-udisks-1/build/6233660/) on my [fork PR](https://github.com/martinpitt/udisks/pull/1). 
Note that this currently uses the default transient packit COPR to build the packages. I would strongly recommend to use them, unless you have a good reason to use your custom one.
If you want "daily builds" done by packit, this needs to happen in a `trigger: commit` (on master branch) job. These are *different* from this `trigger: pull_request` builds, …
> ci: Add Packit configuration for RPM builds on PRs

- modules/iscsi/data/org.freedesktop.UDisks2.iscsi.xml
- modules/iscsi/udisksiscsiutil.c
- modules/iscsi/udiskslinuxiscsisessionobject.c
- modules/iscsi/udiskslinuxiscsisessionobject.h
- modules/iscsi/udiskslinuxmoduleiscsi.c
- src/tests/dbus-tests/test_19_lsm.py
- src/tests/dbus-tests/test_30_iscsi.py
- src/udiskslinuxmanager.c
- src/udiskslinuxprovider.c
A couple more other fixes that I found along the way.
> (mostly) iSCSI iBFT fixes

- src/tests/test_polkitd.py
Similar to https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/167
I was trying to debug the tests failing on current Ubuntu and though it might be the issue but it's not, the problem was  #1112 with linux 6.3. For some reason test_polkitd.py doesn't error out in the testsuite here but it fails if started manually and it should still be the correct behaviour
> tests: start the polkitd mock with the corresponding user if it exists

- .packit.yaml
Default for packit is the latest tag, but we want to use the "next" version we already have set.
> ci: Add custom function to get version for Packit builds

- src/tests/dbus-tests/test_nvme.py
...nobody noticed this mistake, except it was deleting files in /etc/nvme
> tests: Fix Python class invocation in nvme tests

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_80_filesystem.py
- src/udiskslinuxfilesystem.c
Looking at the util-linux-2.39.1 sources only xfs, ext and btrfs probes do have support for reporting filesystem last block. There are many others however that do report filesystem size that would still be beneficial for UDisks to use.
However, for filesystems that we know the two values differ and that are proven to work fine with bd_fs_get_size(), we should still avoid using ID_FS_SIZE. Let's maintain a short internal whitelist.
----
See the previous discussion in #1114 and the feedback in #1139.
Taking `vfat` and `ntfs` as an example, the filesystem size computation looks roughly similar. For the moment it looks like a best effort. The whitelist introduced serves also a blacklist for ID_FS_SIZE for some filesystems.
Fixes #1139
Cc: @mvollmer
> udiskslinuxfilesystem: Use ID_FS_SIZE for filesystems that are not known to report ID_FS_LASTBLOCK

- modules/lvm2/udiskslinuxmodulelvm2.c
- src/tests/dbus-tests/test_20_LVM.py
- src/udiskslinuxprovider.c
- src/udisksmodule.c
- src/udisksmodule.h
Bunch of dirty hacks for the dirty uevent processing hack in the lvm2 module. The lvm2 module uevent handling really needs a complete rewrite...
Fixes #1170
> Generic module uevent handler

- src/tests/dbus-tests/test_20_LVM.py
Device names might change after scsi host rescan and our vdevs need to be populated again.
----
~This is a rather dirty hack and the `find` matching looks fragile. Would be nice to query udevdb directly perhaps, or query udisks even? None of those are 100% reliable.~
> tests: Rescan vdevs after lvm raid tests

- .packit.yaml
- plans/cockpit.fmf
Configure packit to automatically notify relevant Cockpit team members when one of the "cockpit-revdeps" tests fails.
See https://packit.dev/docs/configuration/#failure_comment
---
This wil relieve you from the burden of having to ping us manually. See https://packit.dev/posts/weekly/2023/week-37
> ci: Packit: Enable failure notifications for cockpit tests

- src/udiskslinuxmanager.c
In handle_get_block_devices, call get_block_objects to obtain iface_block_device of all current UDisksLinuxBlockObject, and then obtain the corresponding UDisksLinuxBlockObject's object_path through iface_block_device.iface_block_device is a GDBusInterfaceSkeleton, which saves the object through g_dbus_interface_skeleton_set_object. g_object_add_weak_pointer is used here. This function is not thread-safe.At this time, if other threads are releasing the object, the program will crash.
This scene can be reproduced by quickly plugging and unplugging the USB disk. The core is as follows (the redundant stack is omitted): When accessing object in thread 1, the object is released by thread 2 info threads
Id Target Id Frame
* 1 Thread 0x7f80979e70 (LWP 24559) 0x0000007f8a48dda0 in …
> udiskslinuxmanager:use dbus interface after free

- modules/lvm2/udiskslinuxlogicalvolume.c
- src/udisksdaemon.c
- src/udisksdaemon.h
When a PV is on a LUKS device, lvm reports that device as "/dev/mapper/luks-1234...", which is a symlink to the real device. UDisks2 would miss this and report the segment as having lost its backing PV.
In addition to looking harder for devices, UDisks2 now also distinguises between "PV is gone" and "PV is there but I can't find a D-Bus object for it".
> lvm: Also look at symlinks for segment PVs

- src/udiskslinuxdevice.c
For some reason USB-ATA passthrough devices are sometimes marked as ATA while clearly they're not and our probing ATA commands would fail, spamming the syslog.
Let's ignore such devices for now.
> udiskslinuxdevice: Ignore ID_ATA on USB devices

- modules/lvm2/udiskslvm2daemonutil.c
Legacy code, most of the stuff is now offered by the current API.
Fixes #900
> lvm2: Refactor udisks_daemon_util_lvm2_wipe_block()

- src/udiskslinuxblockobject.c
For some reason even after acquiring a voluntary BSD lock on the device the BLKRRPART ioctl still fails with EBUSY. Wait a couple of msec and everything is fine.
So try harder, several attempts, if busy. There might be number of things going on in the system and it's out of our control even when holding a lock.
Fixes #1204
> udiskslinuxblockobject: Try issuing BLKRRPART ioctl harder

- data/org.freedesktop.UDisks2.xml
Fixes two typos:
- possbile → possible
- assesment → assessment
> doc: fix typos

- modules/btrfs/data/org.freedesktop.UDisks2.btrfs.xml
- modules/btrfs/udiskslinuxfilesystembtrfs.c
- src/tests/dbus-tests/test_btrfs.py
libblockdev provides a method to get the default subvolume id since 2014, with no way to change it. This method does not require any administrative privileges but requires it for setting.
This feels more logical as a property but it requires a method call and I intend to also add a Setter for this. But that requires a libblockdev patch.
---
P.S. I hope the tests succeed. I'm unable to get the tests running on Arch Linux as it uses `lsb_release` and `targetcli`. Targetcli is not available as a package.
> modules/btrfs: add GetDefaultSubvolumeID

- src/udiskslinuxprovider.c
Traditionally the master uevent monitor was bound to a main thread. However with most of the D-Bus object machinery, interface updates, etc. being done in the same thread, lost uevents were spotted on resource-constrained systems.
Better to dedicate a new thread for incoming uevents that are sent to a probing thread right away, effectively acting as a storage queue.
Fixes #1133
> udiskslinuxprovider: Move udev monitor in a separate thread

- src/udiskslinuxdriveata.c
- src/udiskslinuxprovider.c
No real world difference as nobody cares about the result, only added to fully conform to Gio specs and to get rid of these debugging warnings (G_MESSAGES_DEBUG=all):
(udisksd:32988): GLib-GIO-DEBUG: 05:51:26.255: GTask 0x5607c9739930 (source object: 0x5607c97395d0, source tag: (nil)) finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program.
> udiskslinuxprovider: Properly finalize GTaskThreadFunc

- modules/btrfs/data/org.freedesktop.UDisks2.btrfs.xml
- modules/btrfs/udiskslinuxfilesystembtrfs.c
- src/tests/dbus-tests/test_btrfs.py
libblockdev provides a method to set the default subvolume id since
2014. This method does requires administrative privileges as it changes the default mount target subvolume of a btrfs volume.
---
Turns out I was wrong and thought libblockdev did not provide a method for it but it has a slightly different name.
> modules/btrfs: add SetDefaultSubvolumeID

- src/udiskslinuxdrive.c
Thunderbolt ports propagate "removable" attribute to its child devices like external NVMe, so use the attribute to set removable accordingly.
Excerpt from `udevadm info -a /dev/nvme1n1`:
looking at parent device
'/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/0000:04:04.0/0000:3a:00.0/0000:3b:01.0/0000:3c:00.0':
KERNELS=="0000:3c:00.0"
SUBSYSTEMS=="pci"
DRIVERS=="nvme"
...
ATTRS{removable}=="removable"
https://github.com/storaged-project/udisks/issues/793
> udiskslinuxdrive: Mark external NVMe removable

- modules/lvm2/udiskslinuxvolumegroup.c
- src/tests/dbus-tests/test_20_LVM.py
udisks_daemon_util_lvm2_wipe_block is a huge hammer that also tries to call vgreduce and pvscan and does other steps that are not necessary when removing the PV signature after removing the VG.
Fixes: #1228
> lvm: Use pvremove when removing PVs after deleting a VG

- udisks/udisksobjectinfo.c
The translator comments for `udisks_client_get_object_info_for_mdraid` list more `%s` than actually exist in the format string. I suspect this is because they were copied from the section above and not properly adjusted.
> objectinfo: adjust translator comment

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/test_10_basic.py
- src/tests/dbus-tests/test_19_lsm.py
- src/tests/dbus-tests/test_20_LVM.py
- src/tests/dbus-tests/test_30_iscsi.py
- src/tests/dbus-tests/test_40_drive.py
- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_60_partitioning.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/test_btrfs.py
- src/tests/dbus-tests/test_drive_ata.py
- src/tests/dbus-tests/test_loop.py
- src/tests/dbus-tests/test_mdraid.py
- src/tests/dbus-tests/test_nvme.py
- src/tests/dbus-tests/udiskstestcase.py
python-six dependency removed from tests and few small formatting changes in the dbus test suite
> Few small test improvements

- modules/lvm2/jobhelpers.c
- modules/lvm2/udiskslinuxvolumegroup.c
- src/tests/dbus-tests/test_20_LVM.py
'pvremove' doesn't do that which is apparently intentional so we need to do that ourselves.
> lvm: Manually remove removed PVs from the LVM devices file

- udisks/udisksclient.c
Documents that `udisks_client_get_partition_table` can return NULL. This is similar to functions like [`udisks_client_get_drive_for_block`](https://storaged.org/doc/udisks2-api/latest/UDisksClient.html#udisks-client-get-drive-for-block) which document the possible NULL returns.
> client: document NULL return for udisks_client_get_partition_table

- src/udiskslinuxblock.c
This is similar to b79f6840ca82551e672156153b7e13328f0ba19d, which solved the same problem for /etc/crypttab.
> block: Survive a missing /etc/fstab

- src/tests/dbus-tests/test_20_LVM.py
Follow up for #1257, we need a test that works even when there are some old/invalid entries in the devices file.
> tests: Add a more robust test case for LVM devices file

- src/udiskslinuxdriveobject.c
Non-live controllers tend to refuse any I/O anyway.
> udiskslinuxdriveobject: Only refresh health information on live NVMe controllers

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/udiskstestcase.py
> tests: Use seek_realtime when saving journal data

- src/tests/dbus-tests/skip.yml
See also https://github.com/storaged-project/libblockdev/pull/1027
> tests: Skip ExFAT UUID tests with recent exfatprogs

- plans/cockpit.fmf
Cockpit recently renamed/split the optional tests into two storage tests, see https://github.com/cockpit-project/cockpit/pull/20524
> ci: Fix running Cockpit reverse dependency tests

- modules/btrfs/Makefile.am
- modules/iscsi/Makefile.am
- modules/lsm/Makefile.am
- modules/lvm2/Makefile.am
- src/Makefile.am
Use AM_CPPFLAGS instead of ovewriting CPPFLAGS.
CPPFLAGS is a user variable reserved for local modifications. See
https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
> Do not overwrite CPPFLAGS

- .gitignore
Some of our test logs are now compressed so we should ignore these too.
See also #1284
> Add gzipped log files to .gitignore

- src/udiskslinuxfilesystem.c
We already had erofs in the list, squashfs was missing.
> udiskslinuxfilesystem: Add squashfs to well_known_filesystems

- src/tests/integration-test
Like VFAT, EXFAT does not allow some characters in the label. Since version 1.2.5 exfatprogs refuses to set a label with those invalid characters.
Because this changed in version 1.2.5 we cannot assert that setting such label would throw without knowing the exfatprogs version.
While we're touching this part of the test, also document why we're using a shorter label compared to the other filesystems.
> integration-test: Fix change label test with exfatprogs 1.2.5

- plans/tests.fmf
Testing farm sets priority of their repositories to 9 which means the repo is prioritized over all other repositories including our Copr repo with daily builds preventing the latest libblockdev from being installed.
> ci: Remove priority from Testing farm repositories

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
- src/udiskslinuxencryptedhelpers.c
- src/udiskslinuxencryptedhelpers.h
> Add support for specifying extra PBKDF options for LUKS format

- src/tests/dbus-tests/test_40_drive.py
On 6.11 the SCSI debug CD drives are marked as not rotational and for these we report rotation rate 0.
> tests: Fix expected rotation rate for SCSI debug drives in tests

- src/udisksconfigmanager.c
So we can get a little bit more information in the logs when g_key_file_load_from_file fails to load the file.
> Include error message when loading config file fails

- src/udisksata.c
Backport of udev id_ata changes:
https://github.com/systemd/systemd/pull/13654
https://github.com/systemd/systemd/pull/24923
Fixes #1305
> udisksata: Fix sense code format check

- doc/man/udisks.xml.in
- src/udiskslinuxdriveata.c
- src/udiskslinuxdriveobject.c
Refuse any I/O as an intention.
> udiskslinuxdriveata: Respect ID_ATA_SMART_ACCESS=none

- configure.ac
- src/udiskslinuxdevice.c
- src/udiskslinuxdrive.c
- src/udiskslinuxdriveata.c
- src/udiskslinuxdriveobject.c
Looking at the code in udisksata.c vs. udev/ata_id.c it appears to have equal basis, only the udev part has evolved over time. Except of one missing property it has feature parity, is better maintained, runs earlier in the chain and is readily available. There's no reason not to trust it as an authoritative source of information.
The existing probing code needs to stay in UDisks for dm-multipath device use, where udev ata_id is not run.
This needs ID_ATA_READ_LOOKAHEAD support in udev, merged in systemd-257~devel. libudev version is checked during configure and if lower, UDisks will fall back to the old probing approach just for this missing property.
As the udev/ata_id probing code is generally more permissive, it works on qemu-emulated AHCI+IDE devices as a bonus.
Fixes #1153
Fixes #808 …
> udiskslinuxdriveata: Prefer udev ID_ATA_* attributes

- data/builtin_mount_options.conf
> mount options: Add 'map' and 'check' ISO9660 options

- src/udisksspawnedjob.c
Without proper end gtkdoc will include the function in the generated documentation as well.
> Fix docstring for udisks_spawned_job_start

- src/udisksdaemon.c
So we can redirect important messages from libblockdev to our log.
> daemon: Add a logging function for libblockdev

- data/org.freedesktop.UDisks2.xml
- src/tests/dbus-tests/test_70_encrypted.py
- src/udiskslinuxblock.c
- src/udiskslinuxencrypted.c
- src/udiskslinuxencryptedhelpers.c
- src/udiskslinuxencryptedhelpers.h
> Support label when creating and unlocking encrypted devices

- modules/lvm2/udiskslvm2daemonutil.c
Though the voluntary BSD locks cannot be used here due to opening O_EXCL already, let's make several attempts before bailing out.
> lvm2: Try opening for unused device detection harder

- modules/btrfs/Makefile.am
- modules/iscsi/Makefile.am
- modules/lsm/Makefile.am
- modules/lvm2/Makefile.am
GNU libtool accepts either, but slibtool's option parsing is more strict and just ends up passing -export_dynamic to the compiler, which obviously causes an error. Use -export-dynamic to fix building with slibtool.
> build: use -export-dynamic instead of -export_dynamic

- src/main.c
Lowering the priority of normal progress messages makes it easier for users to notice the messages they might need to do something about.
> Change several log levels from NOTICE to INFO

- plans/tests.fmf
Some testing evironments are running in AWS and have the amazon-ec2-utils package installed. This package is well known to cause breakages, shipping udev rules that make absolutely no sense.
The last issue we've been chasing was caused by
/etc/udev/rules.d/60-cdrom_id.rules overriding the system 60-cdrom_id.rules and disabling udev cdrom_id builtin as a result. This caused number of tests failing for no obvious reason.
> ci: Remove amazon-ec2-utils if installed

- misc/udisks-tasks.yml
We can just pass a list of packages to the package module instead. When using "with_items" ansible installs the packages one by one which is significantly slower.
On a system with all dependencies already present:
Before:
real    0m44,649s
user    0m2,319s
sys     0m1,415s
After:
real    0m8,372s
user    0m0,835s
sys     0m0,382s
> misc: Do not use "with_items" when installing packages

- src/tests/dbus-tests/test_50_block.py
- src/tests/dbus-tests/test_70_encrypted.py
- src/tests/dbus-tests/test_80_filesystem.py
- src/tests/dbus-tests/udiskstestcase.py
Multiple DBus tests are trying to backup (and later restore) fstab and crypttab which fails on systems where these config files don't exist.
Fixes: #1364
> tests: Fix running tests on systems without fstab and crypttab

- src/udiskslinuxencryptedhelpers.c
@vojtechtrefny hi I new contributor.
This fixed also fixes memory leak if `ncontext` is not created, `context` will be created successfully, then `context` malloc not free.
> Fixed memleak and misprint check for creating second BDCrypto context

- src/udiskslinuxfilesystemhelpers.c
The private mount done in take_filesystem_ownership() should always default to 'nodev,nosuid' for security and 'errors=remount-ro' for selected filesystem types to handle an corrupted filesystem. This is consistent with mount options calculation for regular mounts.
> udiskslinuxfilesystemhelpers: Mount private mounts with 'nodev,nosuid'

- src/udiskslinuxfilesystem.c
Hiding normal progress messages conserves user attention for when we need them to do something about a problem.
> Use udisks_info() for (un)mount messages

- src/tests/dbus-tests/run_tests.py
- src/tests/dbus-tests/udiskstestcase.py
Since Python 3.14 the default changed to 'forkserver' which requires all shared objects to be picklable which causes some of our filesystem tests that run process as a different user to fail.
> tests: Force Python to use 'fork' method to start child processes

- src/udiskslinuxencrypted.c
The labels on BitLocker can have characters that are not supported in DM names (like '/' which is used in the default label by Windows).
-----
This is just a quick fix, we should check LUKS labels for characters not allowed by device mapper and do some escaping/sanitization there as well. For BitLocker this started to be a problem because util-linux/blkid added support for parsing labels on BitLocker and we automatically pick labels from udev.
> Do not use label for DM name when unlocking BitLocker devices

- src/tests/dbus-tests/test_loop.py
- src/tests/integration-test
echo -e is non-posix extension that doesn't work in all shells.
Fixes: #1413
> tests: Do not use "echo -e" in tests

- src/tests/dbus-tests/safe_dbus.py
- src/tests/dbus-tests/test_job.py
I considered replacing safe_dbus with dasbus (which is what I did in blivet), but I didn't want to introduce a new test dependency. After removing the unused functions, it's just a relatively simple module that should not be that hard to maintain.
> Remove unused functions from safe_dbus 

- src/tests/integration-test
Introduced in mdadm-4.4, this interactive prompt is being displayed:
```
test_md_raid_methods (__main__.MDRaid.test_md_raid_methods) ...
To optimalize recovery speed, it is recommended to enable write-indent bitmap, do you want to enable it now? [y/N]?
```
> integration-test: Force --bitmap=none on mdraid creation

- configure.ac
- packaging/udisks2.spec
(Should be released later today.)
> spec: Bump required version of libblockdev to 3.4
